### ISSUE TITLE
1.14.4 optifabric 0.7.0

### ISSUE THREAD

**Issue by Scheshi** [modmuss50/OptiFabric#107]
[07:48:54] [main/ERROR]: Error encountered during mixin config postInit step'mixins.mm.json': Failed to setup optifine
java.lang.RuntimeException: Failed to setup optifine
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:40) ~[optifabr.jar:?]
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:289) ~[aa4cada5-5f93-4c24-82b9-d9325826bc08.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128) ~[sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:665) ~[sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:512) [sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:409) [sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:385) [sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:280) [sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.7.2+build.174.jar:0.8+build.16+unknown-b16.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174) [fabric-loader-0.7.2+build.174.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) [fabric-loader-0.7.2+build.174.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_231]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:191) [fabric-loader-0.7.2+build.174.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138) [fabric-loader-0.7.2+build.174.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.7.2+build.174.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source) [?:1.8.0_231]
	at pro.gravit.launcher.aBoDEoFlEGeNDS.abODEOfleGeNds(Unknown Source) [Launcher.exe:?]
	at pro.gravit.launcher.aBoDEoFlEGeNDS.main(Unknown Source) [Launcher.exe:?]
Caused by: org.zeroturnaround.zip.ZipException: java.util.zip.ZipException: error in opening zip file
	at org.zeroturnaround.zip.ZipExceptionUtil.rethrow(ZipExceptionUtil.java:11) ~[c885804e-b84d-488a-aa56-c38b4dee7058.jar:?]
	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:522) ~[c885804e-b84d-488a-aa56-c38b4dee7058.jar:?]
	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:472) ~[c885804e-b84d-488a-aa56-c38b4dee7058.jar:?]
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:99) ~[optifabr.jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:28) ~[optifabr.jar:?]
	... 19 more
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_231]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_231]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_231]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_231]
	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:496) ~[c885804e-b84d-488a-aa56-c38b4dee7058.jar:?]
	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:472) ~[c885804e-b84d-488a-aa56-c38b4dee7058.jar:?]
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:99) ~[optifabr.jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:28) ~[optifabr.jar:?]
	... 19 more

**Comment by Scheshi** [comment]
Its update not fix my problem.
@modmuss50
