### ISSUE TITLE
1.14.4 optifabric 0.7.1

### ISSUE THREAD

**Issue by Scheshi** [modmuss50/OptiFabric#108]
java.lang.RuntimeException: Failed to setup optifine
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:40) ~[optifabric-0.7.1.jar:?]
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:289) ~[cb98ad24-a484-4fd6-8c1e-fc0dd4ca290f.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128) ~[sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:665) ~[sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:512) [sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:409) [sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:385) [sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:280) [sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.7.2+build.174.jar:0.8+build.16+unknown-b16.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174) [fabric-loader-0.7.2+build.174.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) [fabric-loader-0.7.2+build.174.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_231]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:191) [fabric-loader-0.7.2+build.174.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138) [fabric-loader-0.7.2+build.174.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.7.2+build.174.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
	at me.modmuss50.optifabric.mod.OptifineInstaller.extract(OptifineInstaller.java:18) ~[optifabric-0.7.1.jar:?]
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:85) ~[optifabric-0.7.1.jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:28) ~[optifabric-0.7.1.jar:?]
	... 19 more
Caused by: java.lang.Exception: MD5 not matching, name: srg/net/minecraft/client/entity/player/AbstractClientPlayerEntity.class, saved: e1c77fd613c8192172f073e9dcfc2613, patched: 1fa7fa29a43f4546c1335ddf7d603f02
	at optifine.Patcher.process(Patcher.java:101) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
	at me.modmuss50.optifabric.mod.OptifineInstaller.extract(OptifineInstaller.java:18) ~[optifabric-0.7.1.jar:?]
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:85) ~[optifabric-0.7.1.jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:28) ~[optifabric-0.7.1.jar:?]
	... 19 more

**Comment by modmuss50** [comment]
Closing, the 1.14.4 version is no longer supported.
