### ISSUE TITLE
Crash With Informed load

### ISSUE THREAD

**Issue by CGDoctor8** [modmuss50/OptiFabric#123]
Crash with latest beta-3
https://paste.ee/p/coRoW

**Comment by modmuss50** [comment]
That paste is no longer found.

**Comment by CGDoctor8** [comment]
https://paste.ee/p/p7J0t
## Crash Log

<details><summary>Log</summary>
<p>


```
MultiMC version: 0.6.10-1340


Minecraft folder is:
/mnt/Games/MultiMC/instances/1.15.23/.minecraft


Java path is:
/usr/lib/jvm/java-13-openjdk-13.0.2.8-1.rolling.fc31.x86_64/bin/java


Java is version 13.0.2, using 64-bit architecture.


Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)

Subsystem: eVga.com. Corp. Device 6276

Kernel driver in use: nvidia

OpenGL version string: 4.6.0 NVIDIA 440.64

Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  /mnt/Games/MultiMC/instances/1.15.23/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  /mnt/Games/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  /mnt/Games/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  /mnt/Games/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  /mnt/Games/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  /mnt/Games/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  /mnt/Games/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  /mnt/Games/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  /mnt/Games/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /mnt/Games/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /mnt/Games/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /mnt/Games/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /mnt/Games/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  /mnt/Games/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /mnt/Games/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  /mnt/Games/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /mnt/Games/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /mnt/Games/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /mnt/Games/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /mnt/Games/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  /mnt/Games/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  /mnt/Games/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /mnt/Games/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  /mnt/Games/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /mnt/Games/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /mnt/Games/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /mnt/Games/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /mnt/Games/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  /mnt/Games/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  /mnt/Games/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  /mnt/Games/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  /mnt/Games/MultiMC/libraries/net/fabricmc/intermediary/1.15.2/intermediary-1.15.2.jar
  /mnt/Games/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.2.0.11/tiny-mappings-parser-0.2.0.11.jar
  /mnt/Games/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar
  /mnt/Games/MultiMC/libraries/net/fabricmc/tiny-remapper/0.2.0.52/tiny-remapper-0.2.0.52.jar
  /mnt/Games/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  /mnt/Games/MultiMC/libraries/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar
  /mnt/Games/MultiMC/libraries/org/ow2/asm/asm/7.3.1/asm-7.3.1.jar
  /mnt/Games/MultiMC/libraries/org/ow2/asm/asm-analysis/7.3.1/asm-analysis-7.3.1.jar
  /mnt/Games/MultiMC/libraries/org/ow2/asm/asm-commons/7.3.1/asm-commons-7.3.1.jar
  /mnt/Games/MultiMC/libraries/org/ow2/asm/asm-tree/7.3.1/asm-tree-7.3.1.jar
  /mnt/Games/MultiMC/libraries/org/ow2/asm/asm-util/7.3.1/asm-util-7.3.1.jar
  /mnt/Games/MultiMC/libraries/net/fabricmc/fabric-loader/0.7.8+build.189/fabric-loader-0.7.8+build.189.jar
  /mnt/Games/MultiMC/libraries/com/mojang/minecraft/1.15.2/minecraft-1.15.2-client.jar

Native libraries:
  /mnt/Games/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-linux.jar
  /mnt/Games/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-linux.jar
  /mnt/Games/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-linux.jar
  /mnt/Games/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-linux.jar
  /mnt/Games/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar
  /mnt/Games/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-linux.jar
  /mnt/Games/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-linux.jar

Mods:
  [❌] AppleSkin-mc1.15.2-forge-1.0.13.jar (disabled)
  [❌] cmdkeybind-1.4.1.jar (disabled)
  [❌] dynamic-fps-1.0.4.jar (disabled)
  [❌] fabric-api-0.5.1+build.294-1.15.jar (disabled)
  [❌] fabric-carpet-1.15.2-1.3.10+v200212.jar (disabled)
  [❌] i-am-very-smart-1.5.0+mc1.14.4.jar (disabled)
  [✔️] informedload-4.0.0
  [❌] itemscroller-fabric-1.15.2-0.15.0-dev.20200212.183513.jar (disabled)
  [❌] LightOverlay-4.3.jar (disabled)
  [❌] litematica-fabric-1.15.2-0.0.0-dev.20200302.233247.jar (disabled)
  [❌] lithium-mc1.15.2-fabric-0.4.6-mod.jar (disabled)
  [❌] malilib-fabric-1.15.2-0.10.0-dev.20+arne.6.jar (disabled)
  [❌] minihud-fabric-1.15.2-0.19.0-dev.20200121.203515.jar (disabled)
  [❌] modmenu-1.10.2+build.32.jar (disabled)
  [✔️] optifabric-1.0.0-beta8
  [❌] phosphor-fabric-mc1.15.2-0.5.2+build.6.jar (disabled)
  [✔️] preview_OptiFine_1.15.2_HD_U_G1_pre12
  [❌] ScreenshotToClipboardFabric-1.0.3.jar (disabled)
  [❌] shulkerboxtooltip-1.4.5+1.15.jar (disabled)
  [❌] SmoothScrollingEverywhere-2.4.jar (disabled)
  [❌] worldedit-forge-mc1.15.2-7.1.0.jar (disabled)
  [❌] WorldEditCUI-1.15.1_01.jar (disabled)

Params:
  --username  --version MultiMC5 --gameDir /mnt/Games/MultiMC/instances/1.15.23/.minecraft --assetsDir /mnt/Games/MultiMC/assets --assetIndex 1.15 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-Xms128m, -Xmx2176m, -Duser.language=en]


Minecraft process ID: 169947


Using onesix launcher.

[01:51:51] [main/INFO]: Loading for game Minecraft 1.15.2
[01:51:51] [main/WARN]: Mod `autoconfig1` (1.2.0+mc1.14.4) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[01:51:51] [main/WARN]: Mod `cloth-config` (0.2.1+build.14) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[01:51:51] [main/INFO]: [FabricLoader] Loading 10 mods: minecraft@1.15.2, mm@2.0, org_slf4j_slf4j-simple@1.7.30, informedload@4.0.0, org_slf4j_slf4j-api@1.7.30, fabricloader@0.7.8+build.189, optifabric@1.0.0-beta8, org_zeroturnaround_zt-zip@1.14, autoconfig1@1.2.0+mc1.14.4, cloth-config@0.2.1+build.14
[01:51:51] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/mnt/Games/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar Service=Knot/Fabric Env=CLIENT
Optifabric is still using the traditional Early Riser initialisation
Found existing patched optifine jar, using that
[01:51:52] [main/INFO]: [OptiFine] *** Reflector Forge ***
[01:51:52] [main/INFO]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[01:51:52] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_773.getTexture
[01:51:52] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1299.getTags
[01:51:52] [main/INFO]: [OptiFine] (Reflector) Field not present: net.minecraft.class_1309.NAMETAG_DISTANCE
[01:51:52] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_3611.getTags
[01:51:52] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_304.setKeyConflictContext
[01:51:52] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_304.setKeyModifierAndCode
[01:51:52] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_304.getKeyModifier
[01:51:52] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_790.fromJson
[01:51:52] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_4696.canRenderInLayer
[01:51:52] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_4696.canRenderInLayer
[01:51:52] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_296$class_298.preDraw
[01:51:52] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_296$class_298.postDraw
[01:51:52] [main/INFO]: [OptiFine] (Reflector) Field not found: World.tileEntitiesToBeRemoved
[01:51:52] [main/INFO]: [OptiFine] *** Reflector Vanilla ***
[01:51:53] [main/FATAL]: Mixin apply failed informedload.mixins.json:MixinTextureManager -> net.minecraft.class_1060: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on actuallyLoadTextures could not find any targets matching 'method_18167' in net.minecraft.class_1060. Using refmap informedLoad-refmap.json [PREINJECT Applicator Phase -> informedload.mixins.json:MixinTextureManager -> Prepare Injections ->  -> handler$zzf000$actuallyLoadTextures(Lnet/minecraft/class_3300;Ljava/util/concurrent/Executor;Ljava/lang/Void;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on actuallyLoadTextures could not find any targets matching 'method_18167' in net.minecraft.class_1060. Using refmap informedLoad-refmap.json [PREINJECT Applicator Phase -> informedload.mixins.json:MixinTextureManager -> Prepare Injections ->  -> handler$zzf000$actuallyLoadTextures(Lnet/minecraft/class_3300;Ljava/util/concurrent/Executor;Ljava/lang/Void;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:543) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:280) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:259) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:139) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:595) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1236) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.7.8+build.189.jar:0.8+build.18+unknown-b18.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174) [fabric-loader-0.7.8+build.189.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) [fabric-loader-0.7.8+build.189.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) [?:?]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Class.java:3062) [?:?]
	at java.lang.Class.getDeclaredFields(Class.java:2249) [?:?]
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) [Optifine-mapped.jar:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:509) [Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_559(class_128.java:101) [intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:54) [intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:414) [intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:129) [intermediary-minecraft-1.15.2-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.7.8+build.189.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138) [fabric-loader-0.7.8+build.189.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.7.8+build.189.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Exiting with -1
org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [informedload.mixins.json:MixinTextureManager] from phase [DEFAULT] in config [informedload.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3062)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2249)
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:509)
	at net.minecraft.class_128.method_559(class_128.java:101)
	at net.minecraft.class_128.<init>(class_128.java:54)
	at net.minecraft.class_128.method_24305(class_128.java:414)
	at net.minecraft.client.main.Main.main(Main.java:129)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on actuallyLoadTextures could not find any targets matching 'method_18167' in net.minecraft.class_1060. Using refmap informedLoad-refmap.json [PREINJECT Applicator Phase -> informedload.mixins.json:MixinTextureManager -> Prepare Injections ->  -> handler$zzf000$actuallyLoadTextures(Lnet/minecraft/class_3300;Ljava/util/concurrent/Executor;Ljava/lang/Void;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:543)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:280)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:259)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:139)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:595)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1236)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 30 more
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:194)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3062)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2249)
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:509)
	at net.minecraft.class_128.method_559(class_128.java:101)
	at net.minecraft.class_128.<init>(class_128.java:54)
	at net.minecraft.class_128.method_24305(class_128.java:414)
	at net.minecraft.client.main.Main.main(Main.java:129)
	... 15 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [informedload.mixins.json:MixinTextureManager] from phase [DEFAULT] in config [informedload.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 30 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on actuallyLoadTextures could not find any targets matching 'method_18167' in net.minecraft.class_1060. Using refmap informedLoad-refmap.json [PREINJECT Applicator Phase -> informedload.mixins.json:MixinTextureManager -> Prepare Injections ->  -> handler$zzf000$actuallyLoadTextures(Lnet/minecraft/class_3300;Ljava/util/concurrent/Executor;Ljava/lang/Void;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:543)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:280)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:259)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:139)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:595)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1236)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 30 more
Process exited with code 255.
MultiMC: Log upload triggered at: 02 Apr 2020 01:51:55 -0600

```

</p>
</details>
