### ISSUE TITLE
Game crashes with Tweakeroo mod.

### ISSUE THREAD

**Issue by Flus1234** [modmuss50/OptiFabric#126]
The game crashes only if there is a Tweakeroo mod in the mods folder. With my 29 other mods it starts without problems.
fabric-loader-0.7.8+build.184-1.15.2
fabric-api-0.4.32+build.292-1.15
malilib-fabric-1.15.2-0.10.0-dev.20+arne.2
optifabric-1.0.0-beta3
preview_OptiFine_1.15.2_HD_U_G1_pre1
tweakeroo-fabric-1.15.2-0.10.0-dev.20200210.005624

**Comment by Flus1234** [comment]
[16:50:22] [main/INFO]: Loading for game Minecraft 1.15.2
[16:50:25] [main/INFO]: [FabricLoader] Loading 40 mods: minecraft@1.15.2, fabric-renderer-api-v1@0.2.10+f08b61330c, fabric-networking-blockentity-v0@0.2.3+e08a73050c, fabric-keybindings-v0@0.1.1+dfdb52d60c, fabricloader@0.7.8+build.184, org_zeroturnaround_zt-zip@1.14, fabric-renderer-indigo@0.2.23+9290e2ed0c, fabric-containers-v0@0.1.3+b7f9825d0c, fabric-dimensions-v1@0.2.4+203491ea0c, fabric-biomes-v1@0.1.5+3b05f68e0c, org_slf4j_slf4j-simple@1.7.30, fabric-crash-report-info-v1@0.1.2+b7f9825d0c, fabric-events-interaction-v0@0.2.7+a1bd31180c, fabric-api-base@0.1.2+b7f9825d0c, fabric-rendering-v0@1.1.0+534104900c, fabric-rendering-v1@0.1.0+534104900c, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d0c, mm@2.0, fabric-resource-loader-v0@0.1.10+06c939b30c, malilib@0.10.0-dev.20+arne.2, tweakeroo@0.10.0-dev.20200210.005624, fabric-textures-v0@1.0.4+821cdba70c, fabric-content-registries-v0@0.1.3+b7f9825d0c, fabric-tag-extensions-v0@0.1.3+abd915800c, optifabric@1.0.0-beta3, fabric-rendering-fluids-v1@0.1.6+12515ed90c, fabric-registry-sync-v0@0.2.6+f3d8141b0c, fabric-commands-v0@0.1.2+b7f9825d0c, fabric-blockrenderlayer-v1@1.1.4+c6a8ea890c, fabric-mining-levels-v0@0.1.1+b7f9825d0c, fabric-renderer-registries-v1@2.0.1+5a0f9a600c, fabric-loot-tables-v1@0.1.5+e08a73050c, fabric-events-lifecycle-v0@0.1.2+b7f9825d0c, fabric@0.4.32+build.292-1.15, org_slf4j_slf4j-api@1.7.30, fabric-particles-v1@0.1.1+dfdb52d60c, fabric-models-v0@0.1.0+dfdb52d60c, fabric-item-groups-v0@0.1.6+ec40b2e10c, fabric-object-builders-v0@0.1.3+e4c9a9c30c, fabric-networking-v0@0.1.7+12515ed90c
[16:50:25] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/flus1/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar Service=Knot/Fabric Env=CLIENT
[16:50:25] [main/WARN]: Reference map 'optifabric-refmap.json' for optifabric.mixins.json could not be read. If this is a development environment you can ignore this message
[16:50:26] [main/WARN]: Reference map 'optifabric-refmap.json' for optifabric.indigofix.mixins.json could not be read. If this is a development environment you can ignore this message
[16:50:26] [main/WARN]: Reference map 'optifabric-refmap.json' for optifabric.optifine.mixins.json could not be read. If this is a development environment you can ignore this message
[16:50:26] [main/INFO]: [OptiFine] *** Reflector Forge ***
[16:50:26] [main/INFO]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient

**Comment by tobilinz** [comment]
I've got the same issue.
[Here is my crashlog](https://github.com/modmuss50/OptiFabric/files/4204569/latest.log)

**Comment by Firion88** [comment]
also having this crash on beta 3 version. to add some more info: 
org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method disableRenderDistanceFog(Lnet/minecraft/class_4184;Lnet/minecraft/class_758$class_4596;FZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in mixins.tweakeroo.json:MixinBackgroundRenderer failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap tweakeroo-fabric-1.15.2-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)

**Comment by Southpaw1496** [comment]
I've got Tweakeroo and my game is running OK

**Comment by Flus1234** [comment]
With new version Optifabric (1.0.0-beta4) problem still exists.

**Comment by Qwerty-Space** [comment]
Is it Tweakeroo that's also causing the Nether lighting glitch too?
![image](https://user-images.githubusercontent.com/6967592/74609203-d209ad00-50df-11ea-8c7a-ac7b55e36b0c.png)


EDIT:  It would appear not

**Comment by Firion88** [comment]
Using optifabric beta 4 and disabling REI still experiencing the same crash

**Comment by Flus1234** [comment]
With new tweakeroo-fabric-1.15.2-0.10.0-dev.20200218.005021 and optifabric-1.0.0-beta4 game work fine.

**Comment by tobilinz** [comment]
It works again! 
Mods:
- optifabric-1.0.0-**beta4**
- preview_OptiFine_1.15.2_HD_U_G1_**pre4**
- tweakeroo-fabric-1.15.2-0.10.0-**dev.20200218.005021**

**Comment by USB-Lord** [comment]
The mod crashes if i put the carpet mod and tweekeroo mod togeather
