### ISSUE TITLE
Crash on launch with requiem. 

### ISSUE THREAD

**Issue by VioletSkies19** [modmuss50/OptiFabric#137]
When launching the game with this and requiem installed the game crashes. (I have tried disabling fast math as the requiem page says to do)

**Comment by modmuss50** [comment]
I need the crash log please

**Comment by SilverDarkBlade** [comment]
03:11:10.215
Preparing to launch minecraft client for fabric-loader-0.7.8+build.184-1.15.2
03:11:11.312
Checking installations.
03:11:11.313
Minecraft client fabric-loader-0.7.8+build.184-1.15.2 is ready to start.
03:11:11.313
Starting!
03:11:11.426
Using default game log configuration client-1.12.xml (outputs XML)
03:11:12.694
Loading for game Minecraft 1.15.2
03:11:15.887
Mod `cotton-client-commands` (0.4.2+1.14.3-SNAPSHOT) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
03:11:15.887
Mod `illuminations` (0.4.0) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
03:11:15.887
Mod `betterdroppeditems` (1.0.1) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
03:11:15.887
[FabricLoader] Loading 82 mods: fabric-renderer-api-v1@0.2.10+f08b61330c, fabric-keybindings-v0@0.1.1+dfdb52d60c, linkedstorage@1.1.1, notenoughcrashes@1.2.2+1.15.1, libcd@2.1.1+1.15.1, fabricloader@0.7.8+build.184, trinkets@2.4.1, satin@1.4.0-nightly.19w46b+build.1, org_zeroturnaround_zt-zip@1.14, fairenchanting@1.1.2, nomadbooks@0.2.1, survivaldebugstick@1.15.2-20w06a-1.0.0, yet_another_gravestone_mod@1.2.1, fabric-containers-v0@0.1.3+b7f9825d0c, fabric-dimensions-v1@0.2.4+203491ea0c, requiem@1.1.4, cotton-client-commands@0.4.2+1.14.3-SNAPSHOT, fabric-api-base@0.1.2+b7f9825d0c, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d0c, diggusmaximus@1.2.6, mm@2.0, fabric-textures-v0@1.0.4+821cdba70c, fabric-rendering-fluids-v1@0.1.6+12515ed90c, cardinal-components-level@2.3.0, playerabilitylib@1.0.0, me_shedaniel_cloth_basic-math@0.3.0, fabric-blockrenderlayer-v1@1.1.4+c6a8ea890c, fabric-renderer-registries-v1@2.0.1+5a0f9a600c, immersive_portals@0.12, fabric-loot-tables-v1@0.1.5+e08a73050c, fabric@0.4.32+build.292-1.15, org_slf4j_slf4j-api@1.7.30, fabric-particles-v1@0.1.1+dfdb52d60c, libblockattributes_core@0.6.3, fabric-networking-v0@0.1.7+12515ed90c, vanilla_parts@1.1.2+1.15.1, libnetworkstack@0.3.2, libmultipart@0.3.3, minecraft@1.15.2, fabric-networking-blockentity-v0@0.2.3+e08a73050c, requiemapi@1.1.4, horsestatsvanilla@1.0.4, modmenu@1.10.1+build.30, illuminations@0.4.0, jankson@2.0.1+j1.2.0, cmdkeybind@1.4.2, betterdroppeditems@1.0.1, fabric-renderer-indigo@0.2.23+9290e2ed0c, autofish@0.8.5, soulshards@1.2.0, fabric-biomes-v1@0.1.5+3b05f68e0c, fabric-crash-report-info-v1@0.1.2+b7f9825d0c, fabric-events-interaction-v0@0.2.7+a1bd31180c, org_slf4j_slf4j-simple@1.7.30, loadcatcher@1.1.0, voidfog@2.2.1+1.15.2, fabric-rendering-v0@1.1.0+534104900c, fabric-rendering-v1@0.1.0+534104900c, cloth-config2@2.8.3, notenoughcrashes-api@1.0.0, fabric-resource-loader-v0@0.1.10+06c939b30c, fabric-content-registries-v0@0.1.3+b7f9825d0c, fabric-tag-extensions-v0@0.1.3+abd915800c, cardinal-components-world@2.3.0, blue_endless_jankson@+, optifabric@1.0.0-beta4, cardinal-components-entity@2.0.3, kirin@1.5.2-1.15.2, fabric-registry-sync-v0@0.2.6+f3d8141b0c, fabric-commands-v0@0.1.2+b7f9825d0c, cardinal-components-base@2.3.0, fabric-mining-levels-v0@0.1.1+b7f9825d0c, fabric-events-lifecycle-v0@0.1.2+b7f9825d0c, grid@1.15-fabric0.4.23-1.5.1, libmultipart_deps_container@0.3.3, fabric-models-v0@0.1.0+dfdb52d60c, fabric-item-groups-v0@0.1.6+ec40b2e10c, fabric-object-builders-v0@0.1.3+e4c9a9c30c, shuffle@1.14.4-1.15.2-20w07a-1.1.1, rubikshotbar@0.1.3, bigbuckets@1.1.0, presencefootsteps@r22+1.15.2
03:11:15.903
Mod `blue_endless_jankson` (+) does not respect SemVer - comparison support is limited.

**Comment by VioletSkies19** [comment]
[03:19:37] [main/INFO]: Loading for game Minecraft 1.15.2
[03:19:40] [main/WARN]: Mod `cotton-client-commands` (0.4.2+1.14.3-SNAPSHOT) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[03:19:40] [main/WARN]: Mod `illuminations` (0.4.0) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[03:19:40] [main/WARN]: Mod `betterdroppeditems` (1.0.1) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[03:19:40] [main/INFO]: [FabricLoader] Loading 82 mods: fabric-renderer-api-v1@0.2.10+f08b61330c, fabric-keybindings-v0@0.1.1+dfdb52d60c, linkedstorage@1.1.1, notenoughcrashes@1.2.2+1.15.1, libcd@2.1.1+1.15.1, fabricloader@0.7.8+build.184, trinkets@2.4.1, satin@1.4.0-nightly.19w46b+build.1, org_zeroturnaround_zt-zip@1.14, fairenchanting@1.1.2, nomadbooks@0.2.1, survivaldebugstick@1.15.2-20w06a-1.0.0, yet_another_gravestone_mod@1.2.1, fabric-containers-v0@0.1.3+b7f9825d0c, fabric-dimensions-v1@0.2.4+203491ea0c, requiem@1.1.4, cotton-client-commands@0.4.2+1.14.3-SNAPSHOT, fabric-api-base@0.1.2+b7f9825d0c, diggusmaximus@1.2.6, mm@2.0, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d0c, fabric-textures-v0@1.0.4+821cdba70c, fabric-rendering-fluids-v1@0.1.6+12515ed90c, cardinal-components-level@2.3.0, playerabilitylib@1.0.0, me_shedaniel_cloth_basic-math@0.3.0, fabric-blockrenderlayer-v1@1.1.4+c6a8ea890c, immersive_portals@0.12, fabric-renderer-registries-v1@2.0.1+5a0f9a600c, fabric-loot-tables-v1@0.1.5+e08a73050c, fabric@0.4.32+build.292-1.15, org_slf4j_slf4j-api@1.7.30, fabric-particles-v1@0.1.1+dfdb52d60c, libblockattributes_core@0.6.3, fabric-networking-v0@0.1.7+12515ed90c, vanilla_parts@1.1.2+1.15.1, libnetworkstack@0.3.2, libmultipart@0.3.3, minecraft@1.15.2, fabric-networking-blockentity-v0@0.2.3+e08a73050c, requiemapi@1.1.4, horsestatsvanilla@1.0.4, modmenu@1.10.1+build.30, illuminations@0.4.0, jankson@2.0.1+j1.2.0, cmdkeybind@1.4.2, betterdroppeditems@1.0.1, fabric-renderer-indigo@0.2.23+9290e2ed0c, autofish@0.8.5, soulshards@1.2.0, fabric-biomes-v1@0.1.5+3b05f68e0c, fabric-crash-report-info-v1@0.1.2+b7f9825d0c, fabric-events-interaction-v0@0.2.7+a1bd31180c, org_slf4j_slf4j-simple@1.7.30, loadcatcher@1.1.0, voidfog@2.2.1+1.15.2, fabric-rendering-v0@1.1.0+534104900c, fabric-rendering-v1@0.1.0+534104900c, cloth-config2@2.8.3, notenoughcrashes-api@1.0.0, fabric-resource-loader-v0@0.1.10+06c939b30c, fabric-content-registries-v0@0.1.3+b7f9825d0c, cardinal-components-world@2.3.0, fabric-tag-extensions-v0@0.1.3+abd915800c, blue_endless_jankson@+, optifabric@1.0.0-beta4, cardinal-components-entity@2.0.3, kirin@1.5.2-1.15.2, fabric-commands-v0@0.1.2+b7f9825d0c, fabric-registry-sync-v0@0.2.6+f3d8141b0c, cardinal-components-base@2.3.0, fabric-mining-levels-v0@0.1.1+b7f9825d0c, fabric-events-lifecycle-v0@0.1.2+b7f9825d0c, grid@1.15-fabric0.4.23-1.5.1, libmultipart_deps_container@0.3.3, fabric-item-groups-v0@0.1.6+ec40b2e10c, fabric-models-v0@0.1.0+dfdb52d60c, fabric-object-builders-v0@0.1.3+e4c9a9c30c, rubikshotbar@0.1.3, shuffle@1.14.4-1.15.2-20w07a-1.1.1, bigbuckets@1.1.0, presencefootsteps@r22+1.15.2
[03:19:40] [main/WARN]: Mod `blue_endless_jankson` (+) does not respect SemVer - comparison support is limited.
[03:19:40] [main/WARN]: Mod `presencefootsteps` (r22+1.15.2) does not respect SemVer - comparison support is limited.
[03:19:40] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/SIlver/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar Service=Knot/Fabric Env=CLIENT
[03:19:40] [main/WARN]: Reference map 'optifabric-refmap.json' for optifabric.mixins.json could not be read. If this is a development environment you can ignore this message
[03:19:41] [main/WARN]: Error loading class: terrails/healthoverlay/HealthRenderer (java.lang.ClassNotFoundException: terrails/healthoverlay/HealthRenderer)
[03:19:42] [main/WARN]: Reference map 'optifabric-refmap.json' for optifabric.indigofix.mixins.json could not be read. If this is a development environment you can ignore this message
[03:19:42] [main/WARN]: Reference map 'optifabric-refmap.json' for optifabric.optifine.mixins.json could not be read. If this is a development environment you can ignore this message
[03:19:43] [main/INFO]: [OptiFine] *** Reflector Forge ***
[03:19:43] [main/INFO]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[03:19:43] [main/FATAL]: Mixin apply failed mixins.requiem.client.json:render.GameRendererMixin -> net.minecraft.class_757: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on unselectPossessedEntity could not find any targets matching 'method_18144' in net.minecraft.class_757. Using refmap requiem-refmap.json [PREINJECT Applicator Phase -> mixins.requiem.client.json:render.GameRendererMixin -> Prepare Injections ->  -> handler$zkm000$unselectPossessedEntity(Lnet/minecraft/class_1297;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on unselectPossessedEntity could not find any targets matching 'method_18144' in net.minecraft.class_757. Using refmap requiem-refmap.json [PREINJECT Applicator Phase -> mixins.requiem.client.json:render.GameRendererMixin -> Prepare Injections ->  -> handler$zkm000$unselectPossessedEntity(Lnet/minecraft/class_1297;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:543) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:280) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:259) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at sun.reflect.GeneratedConstructorAccessor16.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:139) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:595) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1236) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.7.8+build.184.jar:0.8+build.18+unknown-b18.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174) [fabric-loader-0.7.8+build.184.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) [fabric-loader-0.7.8+build.184.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:182) [Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_559(class_128.java:101) [intermediary-fabric-loader-0.7.8+build.184-1.15.2.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:54) [intermediary-fabric-loader-0.7.8+build.184-1.15.2.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:414) [intermediary-fabric-loader-0.7.8+build.184-1.15.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:129) [intermediary-fabric-loader-0.7.8+build.184-1.15.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193) [fabric-loader-0.7.8+build.184.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138) [fabric-loader-0.7.8+build.184.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.7.8+build.184.jar:?]
