### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by athenaonline** [modmuss50/OptiFabric#138]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 1/22/20 3:02 AM
Description: Rendering screen

java.lang.NoSuchMethodError: net.minecraft.class_1060.method_4616(Lnet/minecraft/class_2960;Lnet/minecraft/class_1044;)Z
	at io.github.prospector.modmenu.gui.ModListEntry.bindIconTexture(ModListEntry.java:119)
	at io.github.prospector.modmenu.gui.ModListEntry.render(ModListEntry.java:49)
	at io.github.prospector.modmenu.gui.ModListWidget.renderList(ModListWidget.java:227)
	at net.minecraft.class_350.render(class_350.java:196)
	at io.github.prospector.modmenu.gui.ModListScreen.render(ModListScreen.java:237)
	at net.minecraft.class_757.method_3192(class_757.java:604)
	at net.minecraft.class_310.method_1523(class_310.java:989)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at io.github.prospector.modmenu.gui.ModListEntry.bindIconTexture(ModListEntry.java:119)
	at io.github.prospector.modmenu.gui.ModListEntry.render(ModListEntry.java:49)
	at io.github.prospector.modmenu.gui.ModListWidget.renderList(ModListWidget.java:227)
	at net.minecraft.class_350.render(class_350.java:196)
	at io.github.prospector.modmenu.gui.ModListScreen.render(ModListScreen.java:237)

-- Screen render details --
Details:
	Screen name: io.github.prospector.modmenu.gui.ModListScreen
	Mouse location: Scaled: (333, 171). Absolute: (1334.000000, 685.000000)
	Screen size: Scaled: (640, 360). Absolute: (2560, 1440). Scale factor of 4.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['DepressedPebbles'/79770, l='MpServer', x=-198.26, y=67.74, z=239.11]]
	Chunk stats: Client Chunk Cache: 625, 585
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: -552579272017376965
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-197,65,234), Chunk: (at 11,4,10 in -13,14; contains blocks -208,0,224 to -193,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 10051871 game time, 1000 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:450)
	at net.minecraft.class_310.method_1587(class_310.java:1921)
	at net.minecraft.class_310.method_1514(class_310.java:634)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2202137472 bytes (2100 MB) / 4294967296 bytes (4096 MB) up to 17179869184 bytes (16384 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		amecs: Amecs 1.2.9+1.15-pre5
		appleskin: AppleSkin 1.0.8
		autoconfig1: Auto Config v1 1.2.0+mc1.14.4
		autoconfig1u: Auto Config v1 Updated 1.2.4
		cloth: Cloth Events 1.1.0
		cloth-config: Cloth Config 0.2.1+build.14
		cloth-config2: Cloth Config v2 2.8.3
		csb: Custom Selection Box Fabric 4.1.0
		durabilityviewer: Giselbaers Durability Viewer 1.15-fabric0.4.23-1.7
		fabric: Fabric API 0.4.27+build.286-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d95
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e95
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d95
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d95
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d95
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
		fabric-dimensions-v1: fabric-dimensions-v1 0.2.3+06c939b395
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.2.7+a1bd311895
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825d95
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e195
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+933c24c242
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a730595
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+28f8190f42
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d695
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a730595
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+12515ed995
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.3+e4c9a9c395
		fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d695
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b95
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.7+f3d8141b95
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.21+175d0eb895
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6095
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d95
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed995
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049095
		fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+5341049095
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b375
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd9158095
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba795
		fabricloader: Fabric Loader 0.7.5+build.178
		gbfabrictools: GBfabrictools 1.1.0
		informedload: Informed Load 4.0.0
		lightoverlay: Light Overlay 4.1
		litematica: Litematica 0.0.0-dev.20200121.201842
		malilib: MaLiLib 0.10.0-dev.20+beta.1
		me_shedaniel_cloth_basic-math: basic-math 0.3.0
		minecraft: Minecraft 1.15.2
		modmenu: Mod Menu 1.8.3+build.19
		mousewheelie: Mouse Wheelie 1.3.10+1.15.1-pre1
		orderly: Orderly 1.2.0+build.1-1.15
		org_jetbrains_annotations: annotations 18.0.0
		roughlyenoughitems: Roughly Enough Items 3.3.13
		tweed: Tweed API 2.2.8
		voxelmap: VoxelMap 1.9.14
		waila: Hwyla 1.9.19
	Launched Version: fabric-loader-0.7.5+build.178-1.15.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.66, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7820HK CPU @ 2.90GHz

**Comment by modmuss50** [comment]
I cannot repoduce this.
