### ISSUE TITLE
Cannot run Minecraft

### ISSUE THREAD

**Issue by Arasayari** [modmuss50/OptiFabric#144]
What I have done wrong??
![Untitled](https://user-images.githubusercontent.com/61539598/75512144-0d32a700-5a23-11ea-94c4-1acd209471b3.png)
![Untitled](https://user-images.githubusercontent.com/61539598/75512173-2176a400-5a23-11ea-900b-a75ebfa0ee80.png)
I have all of this requiment. But still cant play?

**Log**
Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_241, using 64-bit architecture.

Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  C:/Users/user/AppData/Roaming/MultiMC/instances/1.14.41/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/user/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/net/fabricmc/intermediary/1.14.4/intermediary-1.14.4.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.2.0.11/tiny-mappings-parser-0.2.0.11.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/net/fabricmc/tiny-remapper/0.2.0.52/tiny-remapper-0.2.0.52.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/org/ow2/asm/asm/7.3.1/asm-7.3.1.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/org/ow2/asm/asm-analysis/7.3.1/asm-analysis-7.3.1.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/org/ow2/asm/asm-commons/7.3.1/asm-commons-7.3.1.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/org/ow2/asm/asm-tree/7.3.1/asm-tree-7.3.1.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/org/ow2/asm/asm-util/7.3.1/asm-util-7.3.1.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/net/fabricmc/fabric-loader/0.7.8+build.184/fabric-loader-0.7.8+build.184.jar
  C:/Users/user/AppData/Roaming/MultiMC/instances/1.14.41/.minecraft/bin/minecraft.jar

Native libraries:
  C:/Users/user/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/user/AppData/Roaming/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] fabric-api-0.4.2+build.246-1.14
  [✔️] optifabric-0.7.1
  [✔️] OptiFine_1.14.4_HD_U_F5_

Jar Mods:
  optifabric-0.7.1 (acf6ba51-e544-4981-af49-cd17f9e3f3cf.jar)
  OptiFine_1.14.4_HD_U_F5_ (0eb7bf47-3f20-4cb9-8448-22170bdced19.jar)
  fabric-api-0.4.2+build.246-1.14 (6c1348d5-2326-4571-b2bf-e694574e042a.jar)

Params:
  --username  --version MultiMC5 --gameDir C:/Users/user/AppData/Roaming/MultiMC/instances/1.14.41/.minecraft --assetsDir C:/Users/user/AppData/Roaming/MultiMC/assets --assetIndex 1.14 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 6848

Using onesix launcher.

[12:04:56] [main/INFO]: Loading for game Minecraft 1.14.4
[12:05:04] [main/INFO]: [FabricLoader] Loading 35 mods: minecraft@1.14.4, fabric-renderer-api-v1@0.1.1+933c24c242, fabric-networking-blockentity-v0@0.2.1+28f8190f42, fabric-keybindings-v0@0.1.1+933c24c242, fabricloader@0.7.8+build.184, org_zeroturnaround_zt-zip@1.13, fabric-renderer-indigo@0.1.14+28f8190f42, fabric-containers-v0@0.1.3+28f8190f42, fabric-dimensions-v1@0.1.1+28f8190f42, fabric-biomes-v1@0.1.1+28f8190f42, org_slf4j_slf4j-simple@1.7.29, fabric-events-interaction-v0@0.1.2+28f8190f42, fabric-crash-report-info-v1@0.1.2+28f8190f42, fabric-api-base@0.1.2+28f8190f42, fabric-rendering-v0@0.1.2+28f8190f42, fabric-rendering-data-attachment-v1@0.1.2+28f8190f42, mm@1.8, fabric-resource-loader-v0@0.1.4+28f8190f42, fabric-textures-v0@0.1.4+933c24c242, fabric-content-registries-v0@0.1.2+28f8190f42, fabric-tag-extensions-v0@0.1.3+d423005742, optifabric@0.7.1, fabric-rendering-fluids-v1@0.1.3+28f8190f42, fabric-commands-v0@0.1.2+28f8190f42, fabric-registry-sync-v0@0.2.3+28f8190f42, fabric-mining-levels-v0@0.1.1+28f8190f42, fabric-loot-tables-v1@0.1.1+28f8190f42, fabric-events-lifecycle-v0@0.1.1+28f8190f42, fabric@0.4.2+build.246-1.14, org_slf4j_slf4j-api@1.7.29, fabric-particles-v1@0.1.1+933c24c242, fabric-models-v0@0.1.0+933c24c242, fabric-item-groups-v0@0.1.1+28f8190f42, fabric-networking-v0@0.1.4+28f8190f42, fabric-object-builders-v0@0.1.2+28f8190f42
[12:05:04] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/user/AppData/Roaming/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar Service=Knot/Fabric Env=CLIENT
Found existing patched optifine jar, using that
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:195)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	... 10 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/util/text/ITextComponent
	at net.optifine.reflect.Reflector.logEntry(Reflector.java:1538)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:156)
	at net.minecraft.class_3268.<clinit>(class_3268.java:82)
	at net.minecraft.class_1066.<init>(class_1066.java:61)
	at net.minecraft.class_310.<init>(class_310.java:351)
	at net.minecraft.client.main.Main.main(Main.java:155)
	... 15 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.util.text.ITextComponent
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 21 more
Exiting with -1
Process exited with code -1.

**Report**
None

**Comment by modmuss50** [comment]
You need to put the mod jars in the mods folder.
