### ISSUE TITLE
Crash on startup with Optifine 1.15.2 HD U pre10

### ISSUE THREAD

**Issue by PixelatedBruh** [modmuss50/OptiFabric#151]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 3/26/20 6:13 PM
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_4668.<clinit>(class_4668.java:79)
	at net.minecraft.class_384.<init>(class_384.java:10)
	at net.minecraft.class_377.<clinit>(class_377.java:24)
	at net.minecraft.class_378.method_2020(class_378.java:152)
	at net.minecraft.class_378$$Lambda$1704/2056436230.apply(Unknown Source)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1118)
	at net.minecraft.class_378.method_2019(class_378.java:151)
	at net.minecraft.class_310.<init>(class_310.java:464)
	at net.minecraft.client.main.Main.main(Main.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [fabric-textures-v0.mixins.json:MixinSpriteAtlasTexture] from phase [DEFAULT] in config [fabric-textures-v0.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 22 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Implicit variable modifier injection failed in net/minecraft/class_1059::beforeSpriteLoad [INJECT Applicator Phase -> fabric-textures-v0.mixins.json:MixinSpriteAtlasTexture -> Apply Injections ->  -> Inject -> fabric-textures-v0.mixins.json:MixinSpriteAtlasTexture->@ModifyVariable::beforeSpriteLoad(Ljava/util/Set;)Ljava/util/Set;]
	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.inject(ModifyVariableInjector.java:167)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:377)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1273)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 22 more
Caused by: org.spongepowered.asm.mixin.injection.modify.InvalidImplicitDiscriminatorException: Found 2 candidate variables but exactly 1 is required.
	at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator.findImplicitLocal(LocalVariableDiscriminator.java:343)
	at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator.findLocal(LocalVariableDiscriminator.java:314)
	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.inject(ModifyVariableInjector.java:158)
	... 31 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_4668.<clinit>(class_4668.java:79)
	at net.minecraft.class_384.<init>(class_384.java:10)
	at net.minecraft.class_377.<clinit>(class_377.java:24)
	at net.minecraft.class_378.method_2020(class_378.java:152)
	at net.minecraft.class_378$$Lambda$1704/2056436230.apply(Unknown Source)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1118)
	at net.minecraft.class_378.method_2019(class_378.java:151)
	at net.minecraft.class_310.<init>(class_310.java:464)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2085471768 bytes (1988 MB) / 2937061376 bytes (2801 MB) up to 9544663040 bytes (9102 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G
	Fabric Mods: 
		fabric: Fabric API 0.5.1+build.294-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d0c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+2ad156310c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+fac69e320c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825d0c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e10c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+b7f9825d0c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+12515ed90c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.3+e4c9a9c30c
		fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d60c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+534104900c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabricloader: Fabric Loader 0.7.8+build.189
		minecraft: Minecraft 1.15.2
		mm: Manningham Mills 2.0
		optifabric: Optifabric 1.0.0-beta4
		org_slf4j_slf4j-api: slf4j-api 1.7.30
		org_slf4j_slf4j-simple: slf4j-simple 1.7.30
		org_zeroturnaround_zt-zip: zt-zip 1.14
	Launched Version: fabric-loader-0.7.8+build.189-1.15.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 436.48, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre10
	OptiFine Build: 20200327-015852
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 436.48
	OpenGlRenderer: GeForce GTX 1060 3GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

The new preview version does not work with the current version of optifabric.

**Comment by MsWolphie** [comment]
Can confirm, got the same issue:

`---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 27/03/2020, 02:58
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at net.minecraft.class_4668.<clinit>(class_4668.java:79)
	at net.minecraft.class_384.<init>(class_384.java:10)
	at net.minecraft.class_377.<clinit>(class_377.java:24)
	at net.minecraft.class_378.method_2020(class_378.java:152)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at net.minecraft.class_378.method_2019(class_378.java:151)
	at net.minecraft.class_310.<init>(class_310.java:464)
	at net.minecraft.client.main.Main.main(Main.java:166)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [fabric-textures-v0.mixins.json:MixinSpriteAtlasTexture] from phase [DEFAULT] in config [fabric-textures-v0.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 29 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Implicit variable modifier injection failed in net/minecraft/class_1059::beforeSpriteLoad [INJECT Applicator Phase -> fabric-textures-v0.mixins.json:MixinSpriteAtlasTexture -> Apply Injections ->  -> Inject -> fabric-textures-v0.mixins.json:MixinSpriteAtlasTexture->@ModifyVariable::beforeSpriteLoad(Ljava/util/Set;)Ljava/util/Set;]
	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.inject(ModifyVariableInjector.java:167)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:377)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1273)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 29 more
Caused by: org.spongepowered.asm.mixin.injection.modify.InvalidImplicitDiscriminatorException: Found 2 candidate variables but exactly 1 is required.
	at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator.findImplicitLocal(LocalVariableDiscriminator.java:343)
	at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator.findLocal(LocalVariableDiscriminator.java:314)
	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.inject(ModifyVariableInjector.java:158)
	... 38 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at net.minecraft.class_4668.<clinit>(class_4668.java:79)
	at net.minecraft.class_384.<init>(class_384.java:10)
	at net.minecraft.class_377.<clinit>(class_377.java:24)
	at net.minecraft.class_378.method_2020(class_378.java:152)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at net.minecraft.class_378.method_2019(class_378.java:151)
	at net.minecraft.class_310.<init>(class_310.java:464)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:166)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 11.0.6, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 1591281128 bytes (1517 MB) / 2478833664 bytes (2364 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx8192m
	Fabric Mods: 
		amecs: Amecs 1.2.9+1.15-pre5
		appleskin: AppleSkin 1.0.8
		autoconfig1u: Auto Config v1 Updated 1.2.4
		carpet: Carpet Mod in Fabric 1.3.15
		cloth: Cloth Events 1.2.0
		cloth-config2: Cloth Config v2 2.10
		dynamicfps: Dynamic FPS 1.1.1
		fabric: Fabric API 0.4.32+build.292-1.15
		fabric-api-base: Fabric API Base 0.1.2+28f8190f42
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d0c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.2.4+203491ea0c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.2.7+a1bd31180c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825de8
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e10c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+933c24c242
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+28f8190f42
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+12515ed90c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.3+e4c9a9c30c
		fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d60c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+534104900c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b395
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+d423005742
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabricloader: Fabric Loader 0.7.8+build.189
		malilib: MaLiLib 0.10.0-dev.20+arne.4
		me_shedaniel_cloth_basic-math: basic-math 0.3.0
		minecraft: Minecraft 1.15.2
		minihud: MiniHUD 0.19.0-dev.20200121.203515
		mm: Manningham Mills 2.0
		modmenu: Mod Menu 1.10.1+build.30
		mousewheelie: Mouse Wheelie 1.4.0+1.15.2-pre1
		optifabric: Optifabric 1.0.0-beta4
		org_jetbrains_annotations: annotations 18.0.0
		org_slf4j_slf4j-api: slf4j-api 1.7.30
		org_slf4j_slf4j-simple: slf4j-simple 1.7.30
		org_zeroturnaround_zt-zip: zt-zip 1.14
		roughlyenoughitems: Roughly Enough Items 3.5.4
		tweed: Tweed API 2.2.8
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1660 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.75, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 8x Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre10
	OptiFine Build: 20200327-015852
	Render Distance Chunks: 18
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 445.75
	OpenGlRenderer: GeForce GTX 1660 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8`

**Comment by MsWolphie** [comment]
Can confirm, got the same issue here

[Here's the crash report on my side](https://github.com/modmuss50/OptiFabric/files/4391028/crash.report.txt)

**Comment by nullableX** [comment]
Yep, getting the same error.

**Comment by andres2100** [comment]
same :c. they dont even say in what version the optifine should be

**Comment by Youggls** [comment]
Yes, I have the same question.

**Comment by JadeTheWah** [comment]
I have the same issue, it stopped when i got rid of the fabric api.

**Comment by DONGYUSEN** [comment]
Well,me tooooo

**Comment by howardt12345** [comment]
I also have the same issue, with the same error messages.

**Comment by kenjiangli** [comment]
same problem

**Comment by silentnoodlemaster** [comment]
I don't know how modmuss50 feels about this but it's common github etiquette to not comment that you have the same issue without adding any new information. You can instead add the 👍 reaction to the original issue comment.

**Comment by DaveyL2013** [comment]
The crash appears to be caused by fabric-textures. I found a quick and dirty way to fix the problem temporarily, but please be aware that this could break other mods due to it's hacky nature. If you open the fabric api jar in 7zip or something similar, you can find a "fabric.mod.json" file, edit it to remove the ending comma from line 110 and remove lines 111-113 entirely. You can also find a META-INF folder, open that and then the jars folder. Then delete the jar named fabric-textures-x.x.x+x.jar from fabric api. If you then save the fabric api jar, this should make optifabric boot with fabric api. Once again, this could break many mods, so use with caution.

**Comment by Youggls** [comment]
> The crash appears to be caused by fabric-textures. I found a quick and dirty way to fix the problem temporarily, but please be aware that this could break other mods due to it's hacky nature. If you open the fabric api jar in 7zip or something similar, you can find a "fabric.mod.json" file, edit it to remove the ending comma from line 110 and remove lines 111-113 entirely. You can also find a META-INF folder, open that and then the jars folder. Then delete the jar named fabric-textures-x.x.x+x.jar from fabric api. If you then save the fabric api jar, this should make optifabric boot with fabric api. Once again, this could break many mods, so use with caution.

This method is suit for me, And it doesn't break other mods so far. Thanks.

**Comment by JTHicks26** [comment]
> The crash appears to be caused by fabric-textures. I found a quick and dirty way to fix the problem temporarily, but please be aware that this could break other mods due to it's hacky nature. If you open the fabric api jar in 7zip or something similar, you can find a "fabric.mod.json" file, edit it to remove the ending comma from line 110 and remove lines 111-113 entirely. You can also find a META-INF folder, open that and then the jars folder. Then delete the jar named fabric-textures-x.x.x+x.jar from fabric api. If you then save the fabric api jar, this should make optifabric boot with fabric api. Once again, this could break many mods, so use with caution.

This fix causes me to be unable to see my hand (including any items) in first person perspective when a shader is enabled. It applies to all 4 custom shaders I've tested and the Optifine internal shaders.

No shader:
https://i.imgur.com/Ue2izHe.png
Shader ([Kappa's Shader](https://rre36.github.io/kappa_shader_web/)):
https://i.imgur.com/y2vCnCp.png

**Comment by Alternus** [comment]
Can confirm the first person rendering issue is unlikely related to the fix proposed. Using just optifabric and optifine 1.15.2 pre10 results in the same issue.

**Comment by qouteall** [comment]
https://github.com/FabricMC/fabric/pull/545

**Comment by modmuss50** [comment]
Ive only just woken up, I havent had a chance to look at the latest version just yet. I want it to work just as much as you guys, just please bare with me.

**Comment by modmuss50** [comment]
Im pushed for time currenlty, but it loaded and shaders worked. Beta 5 going out now

![java_2020-03-27_11-52-27](https://user-images.githubusercontent.com/4324090/77753934-4fe79f00-7022-11ea-8ede-c904460624ab.png)

**Comment by modmuss50** [comment]
Pushed the first version, I still have more fixes I want to do, but like I said im pushed for time right now, so ill look at those over the coming days.

Download it from: 

https://github.com/modmuss50/OptiFabric/releases/tag/1.0.0-beta5

or 

https://www.curseforge.com/minecraft/mc-mods/optifabric/files/2914026

Thanks everyone for the bug reports, keep them coming if you find any issues. 💯
