### ISSUE TITLE
Mod Development - Could not find minecraft jar

### ISSUE THREAD

**Issue by JamsNJellies** [modmuss50/OptiFabric#180]
When using the [Fabric Example Mod](https://github.com/FabricMC/fabric-example-mod/) and adding optifabric, following the instructions in the readme for mod developers except using the latest release of optifabric for newer optifine version compatibility.

```
[15:12:30] [main/ERROR] (mixin) Error encountered during mixin config postInit step'mixins.mm.json': Failed to setup optifine
 java.lang.RuntimeException: Failed to setup optifine
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:48) ~[OptiFabric-1.0.0-beta8@net.fabricmc.yarn.1_15_2.1.15.2+build.15-v2.jar:?]
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:335) ~[Fabric-ASM-v2.0@net.fabricmc.yarn.1_15_2.1.15.2+build.15-v2.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:667) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:440) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:416) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.8.2+build.194@net.fabricmc.yarn.1_15_2.1.15.2+build.15-v2.jar:0.8+build.18+unknown-b18.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174) [fabric-loader-0.8.2+build.194@net.fabricmc.yarn.1_15_2.1.15.2+build.15-v2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) [fabric-loader-0.8.2+build.194@net.fabricmc.yarn.1_15_2.1.15.2+build.15-v2.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) [?:1.8.0_242]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:190) [fabric-loader-0.8.2+build.194@net.fabricmc.yarn.1_15_2.1.15.2+build.15-v2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.8.2+build.194@net.fabricmc.yarn.1_15_2.1.15.2+build.15-v2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.8.2+build.194@net.fabricmc.yarn.1_15_2.1.15.2+build.15-v2.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.0+build.6.jar:?]
Caused by: java.io.FileNotFoundException: Could not find minecraft jar!
	at me.modmuss50.optifabric.mod.OptifineSetup.getMinecraftJar(OptifineSetup.java:238) ~[OptiFabric-1.0.0-beta8@net.fabricmc.yarn.1_15_2.1.15.2+build.15-v2.jar:?]
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:85) ~[OptiFabric-1.0.0-beta8@net.fabricmc.yarn.1_15_2.1.15.2+build.15-v2.jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:34) ~[OptiFabric-1.0.0-beta8@net.fabricmc.yarn.1_15_2.1.15.2+build.15-v2.jar:?]
	... 17 more
```

build.gradle:
```
plugins {
	id 'fabric-loom' version '0.2.7-SNAPSHOT'
	id 'maven-publish'
}

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

archivesBaseName = project.archives_base_name
version = project.mod_version
group = project.maven_group


repositories {
	maven { url 'https://jitpack.io' }
}

dependencies {
	//to change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	// Yay Optifine
	modCompile 'com.github.modmuss50:OptiFabric:1.0.0-beta8'
	compile 'org.zeroturnaround:zt-zip:1.14'
}

processResources {
	inputs.property "version", project.version

	from(sourceSets.main.resources.srcDirs) {
		include "fabric.mod.json"
		expand "version": project.version
	}

	from(sourceSets.main.resources.srcDirs) {
		exclude "fabric.mod.json"
	}
}

// ensure that the encoding is set to UTF-8, no matter what the system default is
// this fixes some edge cases with special characters not displaying correctly
// see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
tasks.withType(JavaCompile) {
	options.encoding = "UTF-8"
}

// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
// if it is present.
// If you remove this task, sources will not be generated.
task sourcesJar(type: Jar, dependsOn: classes) {
	classifier = "sources"
	from sourceSets.main.allSource
}

jar {
	from "LICENSE"
}

// configure the maven publication
publishing {
	publications {
		mavenJava(MavenPublication) {
			// add all the jars that should be included when publishing to maven
			artifact(remapJar) {
				builtBy remapJar
			}
			artifact(sourcesJar) {
				builtBy remapSourcesJar
			}
		}
	}

	// select the repositories you want to publish to
	repositories {
		// uncomment to publish to the local maven
		// mavenLocal()
	}
}
```

gradle.properties:
```
# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://fabricmc.net/use
	minecraft_version=1.15.2
	yarn_mappings=1.15.2+build.15
	loader_version=0.8.2+build.194

# Mod Properties
	mod_version = 1.0.0
	maven_group = net.fabricmc
	archives_base_name = fabric-example-mod

# Dependencies
	# currently not on the main fabric site, check on the maven: https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api
	fabric_version=0.5.1+build.294-1.15
```

**Comment by modmuss50** [comment]
I need to update it to support loom 0.2.7

**Comment by modmuss50** [comment]
Fixed
