### ISSUE TITLE
1.15.2 OptiFabric 1.0.0-beta8 ZipException

### ISSUE THREAD

**Issue by ColaIan** [modmuss50/OptiFabric#188]
Log:
```[00:27:38] [main/INFO]: Loading for game Minecraft 1.15.2
[00:27:41] [main/WARN]: Mod `replaymod` (1.15.2-2.3.0-b1) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[00:27:41] [main/INFO]: [FabricLoader] Loading 43 mods: minecraft@1.15.2, fabric-networking-blockentity-v0@0.2.3+e08a73050c, fabric-renderer-api-v1@0.2.10+f08b61330c, fabric-keybindings-v0@0.1.1+dfdb52d60c, modmenu@1.10.2+build.32, fabricloader@0.8.2+build.194, org_zeroturnaround_zt-zip@1.14, fabric-renderer-indigo@0.2.23+9290e2ed0c, fabric-containers-v0@0.1.3+b7f9825d0c, fabric-dimensions-v1@0.3.0+2ad156310c, fabric-biomes-v1@0.1.5+3b05f68e0c, org_slf4j_slf4j-simple@1.7.30, fabric-crash-report-info-v1@0.1.2+b7f9825d0c, fabric-events-interaction-v0@0.3.0+fac69e320c, fabric-api-base@0.1.2+b7f9825d0c, fabric-rendering-v0@1.1.0+534104900c, fabric-rendering-v1@0.1.0+534104900c, replaymod@1.15.2-2.3.0-b1, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d0c, mm@2.0, fabric-resource-loader-v0@0.1.10+06c939b30c, malilib@0.10.0-dev.20+arne.4, fabric-textures-v0@1.0.4+821cdba70c, worldeditcui@1.15.1_01, fabric-content-registries-v0@0.1.3+b7f9825d0c, fabric-tag-extensions-v0@0.1.3+abd915800c, optifabric@1.0.0-beta8, fabric-rendering-fluids-v1@0.1.6+12515ed90c, litematica@0.0.0-dev.20200302.233247, fabric-registry-sync-v0@0.2.6+f3d8141b0c, fabric-commands-v0@0.1.2+b7f9825d0c, fabric-blockrenderlayer-v1@1.1.4+c6a8ea890c, fabric-mining-levels-v0@0.1.1+b7f9825d0c, fabric-renderer-registries-v1@2.0.1+5a0f9a600c, fabric-loot-tables-v1@0.1.5+e08a73050c, fabric-events-lifecycle-v0@0.1.2+b7f9825d0c, fabric@0.5.1+build.294-1.15, org_slf4j_slf4j-api@1.7.30, fabric-particles-v1@0.1.1+dfdb52d60c, fabric-models-v0@0.1.0+dfdb52d60c, fabric-item-groups-v0@0.1.6+ec40b2e10c, fabric-object-builders-v0@0.1.3+e4c9a9c30c, fabric-networking-v0@0.1.7+12515ed90c
[00:27:41] [main/WARN]: Mod `worldeditcui` (1.15.1_01) does not respect SemVer - comparison support is limited.
[00:27:41] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/ColaIan/Desktop/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar Service=Knot/Fabric Env=CLIENT
[00:27:41] [main/WARN]: Reference map 'mixins.nonmmlauncher.replaymod.refmap.json' for mixins.nonmmlauncher.replaymod.json could not be read. If this is a development environment you can ignore this message
[00:27:43] [main/ERROR]: Error encountered during mixin config postInit step'mixins.mm.json': Failed to setup optifine
java.lang.RuntimeException: Failed to setup optifine
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:48) ~[optifabric-1.0.0-beta8.jar:?]
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:335) ~[c8ece861-45bf-4839-aa3f-7475cb5d3062.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:667) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:440) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:416) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.8.2+build.194.jar:0.8+build.18+unknown-b18.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) [fabric-loader-0.8.2+build.194.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_241]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:190) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.8.2+build.194.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: org.zeroturnaround.zip.ZipException: java.util.zip.ZipException: error in opening zip file
	at org.zeroturnaround.zip.ZipExceptionUtil.rethrow(ZipExceptionUtil.java:11) ~[7f3bbe0f-5bfa-494c-805b-d7cd5419e66a.jar:?]
	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:522) ~[7f3bbe0f-5bfa-494c-805b-d7cd5419e66a.jar:?]
	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:472) ~[7f3bbe0f-5bfa-494c-805b-d7cd5419e66a.jar:?]
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:99) ~[optifabric-1.0.0-beta8.jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:34) ~[optifabric-1.0.0-beta8.jar:?]
	... 24 more
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_241]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_241]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_241]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_241]
	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:496) ~[7f3bbe0f-5bfa-494c-805b-d7cd5419e66a.jar:?]
	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:472) ~[7f3bbe0f-5bfa-494c-805b-d7cd5419e66a.jar:?]
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:99) ~[optifabric-1.0.0-beta8.jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:34) ~[optifabric-1.0.0-beta8.jar:?]
	... 24 more
[00:27:43] [main/WARN]: Error loading class: net/optifine/render/ChunkVisibility (java.lang.ClassNotFoundException: net/optifine/render/ChunkVisibility)
[00:27:43] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
[00:27:43] [main/WARN]: Error loading class: net/optifine/shaders/ShadersRender (java.lang.ClassNotFoundException: net/optifine/shaders/ShadersRender)
[00:27:43] [main/WARN]: Error loading class: net/optifine/shaders/Shaders (java.lang.ClassNotFoundException: net/optifine/shaders/Shaders)
[00:27:44] [main/INFO]: Setting user: ColaIan
[00:27:47] [main/INFO]: Definitely not up to no good
[00:27:47] [main/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[00:27:47] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[00:27:48] [Thread-45/INFO]: Cannot offer OpenEye, server returned: 404 Not Found
[00:27:49] [main/WARN]: Removed resource pack file/1.15-r1.zip from options because it doesn't seem to exist anymore
[00:27:49] [main/WARN]: Removed resource pack file/Faithful+3D+1.15.x+v2.1.zip from options because it doesn't seem to exist anymore
[00:27:49] [main/WARN]: Removed resource pack file/Faithful Dark UI 1.14.4.zip from options because it doesn't seem to exist anymore
[00:27:49] [main/WARN]: Removed resource pack file/3D-Noteblock-Displays-1.14-V2.2.zip from options because it doesn't seem to exist anymore
[00:27:49] [main/WARN]: Removed resource pack file/Glass Doors Addon for Faithful 1.14.zip from options because it doesn't seem to exist anymore
[00:27:49] [main/WARN]: Removed resource pack file/VanillaTweaks_r655960.zip from options because it doesn't seem to exist anymore
[00:27:50] [main/INFO]: Narrator library for x64 successfully loaded
[00:27:51] [main/INFO]: Reloading ResourceManager: Default, Fabric Networking Block Entity (v0), Fabric Renderer API (v1), Fabric Key Bindings (v0), Mod Menu, Fabric Renderer - Indigo, Fabric Containers (v0), Fabric Biomes (v1), Fabric Crash Report Info (v1), Fabric Events Interaction (v0), Fabric API Base, Fabric Rendering (v0), Fabric Rendering (v1), replaymod_lang, Replay Mod, Fabric Rendering Data Attachment (v1), Manningham Mills, Fabric Resource Loader (v0), MaLiLib, Fabric Textures (v0), WorldEditCUI, Fabric Content Registries (v0), Fabric Tag Extensions (v0), Optifabric, Fabric Rendering Fluids (v1), Litematica, Fabric Registry Sync (v0), Fabric Commands (v0), Fabric BlockRenderLayer Registration (v1), Fabric Mining Levels (v0), Fabric Renderer Registries (v1), Fabric Loot Tables (v1), Fabric Events Lifecycle (v0), Fabric API, Fabric Models (v0), Fabric Item Groups (v0), Fabric Object Builders (v0), Fabric Networking (v0)
[00:27:58] [main/INFO]: OpenAL initialized.
[00:27:58] [main/INFO]: Sound engine started
[00:27:59] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[00:27:59] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[00:27:59] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[00:27:59] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[00:27:59] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[00:27:59] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[00:27:59] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[00:27:59] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[00:27:59] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[00:27:59] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
```

**Comment by modmuss50** [comment]
Try deleting the .optifine folder. one of you jar files is invalid

**Comment by deeg05** [comment]
Still no good :(

**Comment by ColaIan** [comment]
@modmuss50 It's still not working
![image](https://user-images.githubusercontent.com/43201383/81923082-b135f280-960f-11ea-9e1b-5979f39d8903.png)
I tried removing .optifine folder and installed optifine 1.15.2 G1 pre 16 today, but it still doesn't work.


P.S. Sorry for late reply, but it frustrates me when developers close tickets before the OP stating that the problem is fixed.
