### ISSUE TITLE
Anyone know what this issue means? I also get this message: "The game crashed whilst initializing game Error: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 'ninjaphenix-container-lib'

### ISSUE THREAD

**Issue by BlazingSolace** [modmuss50/OptiFabric#233]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 04.07.20 11:19
Description: Initializing game

net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 'ninjaphenix-container-lib'
	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:193)
	at net.fabricmc.loader.FabricLoader.getEntrypointContainers(FabricLoader.java:228)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:44)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:425)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:64)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101)
	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:186)
	... 13 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method markModdedStack(Lnet/minecraft/class_2487;Lnet/minecraft/class_1799;)Lnet/minecraft/class_2487; in mixins.cardinal_components_item.json:common.MixinPacketByteBuf failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap cardinal-components-item-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 26 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:193)
	at net.fabricmc.loader.FabricLoader.getEntrypointContainers(FabricLoader.java:228)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:44)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:425)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1606272744 bytes (1531 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin 1.0.11
		artifice: Artifice 0.8.0+1.16-rc1
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		bambootweaks: Bamboo Tweaks unspecified
		blue_endless_jankson: jankson +
		boot: BootZ 1.3.1
		campanion: Campanion 1.1.10+build.24
		cardinal-components-base: Cardinal Components API (base) 2.4.1
		cardinal-components-entity: Cardinal Components API (entities) 2.4.1
		cardinal-components-item: Cardinal Components API (items) 2.4.0
		cardinal-components-world: Cardinal Components API (worlds) 2.4.0-nightly.1.16-rc1.build.2
		chainmail: Chainmail 0.3.0
		cloth-api: Cloth API 1.0.6
		cloth-armor-api-v1: Cloth Armor API v1 1.0.6
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.6
		cloth-common-events-v1: Cloth Common Events v1 1.0.6
		cloth-config2: Cloth Config v4 4.5.6
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.0.6
		cloth-scissors-api-v1: Cloth Scissors API v1 1.0.6
		cloth-utils-v1: Cloth Utils v1 1.0.6
		com_electronwill_night-config_core: core 3.6.0
		com_electronwill_night-config_toml: toml 3.6.0
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		creativebuttonmover: Creative Button Mover 0.2.5
		crimsonmoon: Crimson Moon 1.1.0-1.16
		diggusmaximus: Diggus Maximus 1.2.11-1.16
		equip: EquipZ 1.6.1
		expandedstorage: ExpandedStorage 5.3.14
		fabric: Fabric API 0.14.1+build.372-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c7c
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-furnaces: Fabric Furnaces 1.3.0-1.16.1
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+e16a977402
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.0.0+b0993bc102
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.10+059ea86602
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.5+e00ecb5f02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.0+da175ad602
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.2+4d66bed502
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.0.1+f362c86e02
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.4+5794386e02
		fabricloader: Fabric Loader 0.8.9+build.203
		grindenchantments: Grind Enchantments 1.1.1+1.16.1
		gubbins: Gubbins 1.1.1-1.16.1
		harvest: Harvest 1.2.12
		inmis: Inmis 1.0.2-1.16
		inventorysorter: Inventory Sorter 1.6.7-1.16
		iron-jetpacks: Iron Jetpacks 0.2.3
		jankson: Jankson 3.0.0+j1.2.0
		kyrptconfig: Kytpt Config 1.0.4-1.16
		leadvillagers: Lead Villagers 2.1.0+mc1.16.1
		libcd: LibCapableData 2.4.1+1.16-pre2
		libgui: LibGui 2.0.1+1.16.1
		libstructure: Libstructure 1.3
		minecraft: Minecraft 1.16.1
		mm: Manningham Mills 2.0
		modmenu: Mod Menu 1.12.2+build.17
		mostructures: Mo' Structures 1.0.0-pre2+mc.1.16
		ninjaphenix-container-lib: NinjaPhenix's Container Library 1.1.4
		optifabric: Optifabric 1.1.0-beta1
		org_aeonbits_owner_owner: owner 1.0.12
		org_javassist_javassist: javassist 3.26.0-GA
		org_reflections_reflections: reflections 0.9.12
		org_slf4j_slf4j-api: slf4j-api 1.7.30
		org_slf4j_slf4j-simple: slf4j-simple 1.7.30
		org_zeroturnaround_zt-zip: zt-zip 1.14
		parchment: Parchment 1.0.2+1.15.2
		phosphor: Phosphor 0.6.0+build.7
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		ringsofascension: Rings of Ascension 1.0.3
		rotten: FleshZ 1.2.2
		roughlyenoughitems: Roughly Enough Items 4.6.6
		rpgstats: RPGStats 1.1.4+1.16.1
		satin: Satin 1.4.0-nightly.1.16-pre5+build.1
		simpleteleporters: Simple Teleporters 2.2.0
		spinnery: Spinnery 3.0.40
		stuffz: StuffZ 2.2.1
		tacocraft: TacoCraft 1.3.0+mc.1.16
		team_reborn_energy: Energy 0.1.0
		trinkets: Trinkets 2.6.2
		universalcomponents: Universal Components 0.7.2+1.16-pre2
		vanilla-hammers: Vanilla Hammers ${version}
		vanilladeathchest: VanillaDeathChest 1.16.1-1.11.0.2-fabric
		voxelmap: VoxelMap 1.10.3
		waila: Hwyla 1.9.22
		walljump: Wall-Jump! 1.3.3+1.16.1
	Launched Version: fabric-loader-0.8.9+build.203-1.16.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.16.1_HD_U_G2_pre2
	OptiFine Build: 20200703-234202
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 0

**Comment by rosalinadev** [comment]
Well it's written on the first line that it couldn't load what it needed from 'ninjaphenix-container-lib', you could always try without this mod (and probably related mods)

**Comment by BlazingSolace** [comment]
I was thinking about that too, but I don't think I have that mod installed. Or, I don't think I have a mod installed by that name at least.

**Comment by BlazingSolace** [comment]
I think the problem is from the Expanded storage mod.

**Comment by Processhf** [comment]
It's a duplicate of my issue. ExpandedStorage uses the Mixin library just like a ton of mods on Fabric, and there's currently a problem with optifabric not working with Mixin it seems.
