### ISSUE TITLE
Crash after opening the world

### ISSUE THREAD

**Issue by ChARCOOL** [modmuss50/OptiFabric#234]
[15:17:13] [main/ERROR]: Injection error: LVT in net/minecraft/class_757::method_3192(FJZ)V has incompatible changes at opcode 546 in callback net/minecraft/class_757::renderScreen.
Expected: [I, I, Lnet/minecraft/class_4587;]
   Found: [I, Lnet/minecraft/class_1041;]

[15:19:03] [Worker-Main-17/ERROR]: Couldn't download http texture: java.net.SocketException: Malformed reply from SOCKS server

[15:19:03] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalAccessError: tried to access field net.minecraft.class_3898$class_3208.field_18247 from class net.minecraft.class_3898
	at net.minecraft.class_3898.method_18713(class_3898.java:2249) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3215.method_14096(class_3215.java:467) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3244.method_12063(class_3244.java:867) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_2828.method_12272(class_2828.java:122) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_2828$class_2830.method_11054(class_2828.java:18) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:34) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:172) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:763) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:154) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:134) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:745) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:739) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:723) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[15:19:03] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Kudret\MultiMC\instances\1.16.1\.minecraft\crash-reports\crash-2020-07-04_15.19.03-server.txt

java.lang.IllegalAccessError: tried to access field net.minecraft.class_3898$class_3208.field_18247 from class net.minecraft.class_3898
	at net.minecraft.class_3898.method_18713(class_3898.java:2249)
	at net.minecraft.class_3215.method_14096(class_3215.java:467)
	at net.minecraft.class_3244.method_12063(class_3244.java:867)
	at net.minecraft.class_2828.method_12272(class_2828.java:122)
	at net.minecraft.class_2828$class_2830.method_11054(class_2828.java:18)
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:34)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:172)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:763)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:154)
	at net.minecraft.class_1255.method_16075(class_1255.java:134)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:745)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:739)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:723)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2560711728 bytes (2442 MB) / 3728211968 bytes (3555 MB) up to 7532969984 bytes (7184 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8081m
	Fabric Mods: 
		appleskin: AppleSkin 1.0.11
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		betterdroppeditems: Better Dropped Items 1.2.1-1.16
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.4
		cloth-config2: Cloth Config v4 4.5.6
		com_squareup_moshi_moshi: moshi 1.9.2
		com_squareup_okio_okio: okio 1.16.0
		dark-loading-screen: Dark Loading Screen 1.3.0
		dataloader: Data Loader 2.1.0+mc1.16.1
		easiervillagertrading: EasierVillagerTrading 1.16-fabric0.13.1-1.5.1
		fabric: Fabric API 0.14.1+build.372-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c7c
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+e16a977402
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-language-kotlin: Fabric Language Kotlin 1.3.71+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.0.0+b0993bc102
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.10+059ea86602
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.5+e00ecb5f02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.0+da175ad602
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.2+4d66bed502
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.0.1+f362c86e02
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.4+5794386e02
		fabricloader: Fabric Loader 0.8.8+build.202
		fabritone: Fabritone 1.5.3
		inventoryprofiles: Inventory Profiles 0.2.0
		kirin: Kirin UI 1.6.4-1.16-rc1-1.16-SNAPSHOT
		lightoverlay: Light Overlay 5.4.0
		lithium: Lithium 0.5.0-rc1
		minecraft: Minecraft 1.16.1
		mm: Manningham Mills 2.0
		modmenu: Mod Menu 1.12.2+build.17
		modupdater: ModUpdater 1.1.7+1.16.1
		optifabric: Optifabric 1.1.0-beta2
		orderly: Orderly 2.0.0-alpha.10-1.16
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.71
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.71
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.71
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.71
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.5
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.5
		org_slf4j_slf4j-api: slf4j-api 1.7.30
		org_slf4j_slf4j-simple: slf4j-simple 1.7.30
		org_zeroturnaround_zt-zip: zt-zip 1.14
		phosphor: Phosphor 0.6.0+build.7
		presencefootsteps: Presence Footsteps r26+1.16-rc1
		prone: prone 0.1.0
		roughlyenoughitems: Roughly Enough Items 4.6.6
		sneak-through-berries: Sneak Through Berries 1.0.1
		voxelmap: VoxelMap 1.10.3
		wurst: Wurst Client v7.3-MC1.16.1
	Player Count: 1 / 8; [class_3222['kudretdavudoff'/180, l='ServerLevel[Fabric World]', x=809.80, y=69.00, z=2735.16]]
	Data Packs: vanilla, fabric/fabric-tool-attribute-api-v1, file/double-door.zip (incompatible), file/old-fishing.zip (incompatible), file/tree-capitator.zip, file/vein-mining.zip (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
	OptiFine Version: OptiFine_1.16.1_HD_U_G2_pre2
	OptiFine Build: 20200703-234202
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 451.48
	OpenGlRenderer: GeForce 940MX/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Kudret\MultiMC\instances\1.16.1\.minecraft\crash-reports\crash-2020-07-04_15.19.03-server.txt
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by ghost** [comment]
People are reporting that lithium isn't compatible with optifabric.
See:https://github.com/jellysquid3/lithium-fabric/issues/73

**Comment by cs127** [comment]
Yes, it's because of lithium.
