### ISSUE TITLE
Game crash after open a world

### ISSUE THREAD

**Issue by DancingSnow0517** [modmuss50/OptiFabric#236]
Logs:
[23:40:54] [Server thread/INFO]: Starting integrated minecraft server version 1.16.1
[23:40:54] [Server thread/INFO]: Generating keypair
[23:40:55] [Server thread/INFO]: create world dimension: minecraft:overworld (seed: -6755175932281729728)
[23:40:55] [Server thread/INFO]: create world dimension: minecraft:the_nether (seed: -6755175932281729728)
[23:40:55] [Server thread/INFO]: create world dimension: minecraft:the_end (seed: -6755175932281729728)
[23:40:55] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[23:40:55] [main/INFO]: 准备生成区域中：0%
[23:40:55] [main/INFO]: 准备生成区域中：0%
[23:40:56] [main/INFO]: 准备生成区域中：44%
[23:40:57] [main/INFO]: 准备生成区域中：83%
[23:40:57] [main/INFO]: 准备生成区域中：83%
[23:40:57] [main/INFO]: 准备生成区域中：83%
[23:40:58] [main/INFO]: 准备生成区域中：95%
[23:40:58] [main/INFO]: 准备生成区域中：98%
[23:40:58] [main/INFO]: Time elapsed: 3607 ms
[23:40:58] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.fabric.FabricPlatform with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@18aa9812]
[23:40:59] [Server thread/INFO]: Registering commands with com.sk89q.worldedit.fabric.FabricPlatform
[23:40:59] [Server thread/INFO]: Reloaded configs for mousewheelie (universal/world)
[23:40:59] [Server thread/INFO]: Reloaded configs for tweed (universal/world)
[23:40:59] [Server thread/INFO]: Changing view distance to 11, from 10
[23:41:01] [Server thread/INFO]: DancingSnow[local:E:6bccd256] logged in with entity id 208 at (-119.69999998807907, 84.0, 28.186605557349512)
[23:41:01] [Server thread/INFO]: DancingSnow加入了游戏
[23:41:01] [Server thread/INFO]: Saving and pausing game...
[23:41:01] [Server thread/INFO]: Saving chunks for level 'ServerLevel[测试]'/minecraft:overworld
[23:41:02] [Server thread/INFO]: Saving chunks for level 'ServerLevel[测试]'/minecraft:the_nether
[23:41:02] [Server thread/INFO]: Saving chunks for level 'ServerLevel[测试]'/minecraft:the_end
[23:41:03] [main/INFO]: Requested config sync for mousewheelie
[23:41:03] [main/INFO]: Requested config sync for tweed
[23:41:03] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalAccessError: tried to access field net.minecraft.class_3898$class_3208.field_18247 from class net.minecraft.class_3898
	at net.minecraft.class_3898.method_18713(class_3898.java:2249) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3215.method_14096(class_3215.java:467) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3244.method_12063(class_3244.java:867) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_2828.method_12272(class_2828.java:122) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_2828$class_2830.method_11054(class_2828.java:18) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:34) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:172) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:763) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:154) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:134) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:745) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:739) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:150) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:724) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bdf000$modifiedRunLoop(MinecraftServer.java:4805) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:653) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[23:41:03] [Server thread/ERROR]: This crash report has been saved to: D:\DongJing\Minecraft\MultiMC\instances\1.16.1\.minecraft\crash-reports\crash-2020-07-04_23.41.03-server.txt
[23:41:03] [Server thread/INFO]: Unregistering com.sk89q.worldedit.fabric.FabricPlatform from WorldEdit
[23:41:03] [Server thread/INFO]: Stopping server
[23:41:03] [Server thread/INFO]: Saving players
[23:41:03] [Server thread/INFO]: DancingSnow lost connection: 连接中止
[23:41:03] [Server thread/INFO]: DancingSnow退出了游戏
[23:41:05] [REI-SyncRecipes/INFO]: Reloading REI, registered 2 plugins: roughlyenoughitems:default_auto_crafting_plugin, roughlyenoughitems:default_plugin
[23:41:05] [Server thread/INFO]: Stopping singleplayer server as player logged out
[23:41:05] [Server thread/INFO]: Saving worlds
[23:41:05] [Server thread/INFO]: Saving chunks for level 'ServerLevel[测试]'/minecraft:overworld
[23:41:05] [REI-SyncRecipes/INFO]: Applied Check Tags for potion in 1ms.
[23:41:05] [REI-SyncRecipes/INFO]: Refiltered 0 entries in 1ms.
[23:41:05] [REI-SyncRecipes/INFO]: Reloaded 1246 stack entries, 1333 recipes displays, 3 exclusion zones suppliers, 5 overlay deciders, 1 visibility handlers and 13 categories (合成, 烧炼, 烟熏, 熔炼, 营火, 切石, 燃料, 酿造, 堆肥, 去皮, 锻造, 信标基地, 信息) in 2428ms.
[23:41:06] [main/INFO]: DurabilityViewer did not find Trinkets API
[23:41:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (测试): All chunks are saved
[23:41:06] [Server thread/INFO]: Saving chunks for level 'ServerLevel[测试]'/minecraft:the_nether
[23:41:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[23:41:06] [Server thread/INFO]: Saving chunks for level 'ServerLevel[测试]'/minecraft:the_end
[23:41:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[23:41:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (测试): All chunks are saved
[23:41:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[23:41:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[23:41:06] [main/INFO]: [CHAT] §ENo waypoints exist for this world/server.
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 7/4/20 11:41 PM
Description: Exception in server tick loop

java.lang.IllegalAccessError: tried to access field net.minecraft.class_3898$class_3208.field_18247 from class net.minecraft.class_3898
	at net.minecraft.class_3898.method_18713(class_3898.java:2249)
	at net.minecraft.class_3215.method_14096(class_3215.java:467)
	at net.minecraft.class_3244.method_12063(class_3244.java:867)
	at net.minecraft.class_2828.method_12272(class_2828.java:122)
	at net.minecraft.class_2828$class_2830.method_11054(class_2828.java:18)
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:34)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:172)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:763)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:154)
	at net.minecraft.class_1255.method_16075(class_1255.java:134)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:745)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:739)
	at net.minecraft.class_1255.method_18857(class_1255.java:150)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:724)
	at net.minecraft.server.MinecraftServer.handler$bdf000$modifiedRunLoop(MinecraftServer.java:4805)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:653)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1195600008 bytes (1140 MB) / 2793930752 bytes (2664 MB) up to 5249695744 bytes (5006 MB)
	CPUs: 6
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx5632m
	Fabric Mods: 
		amecsapi: Amecs API 1.0.2+1.16-rc1
		appleskin: AppleSkin 1.0.11
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		autofish: Autofish 0.8.6
		bbor: BoundingBoxOutlineReloaded 2.3-1.16.1
		carpet: Carpet Mod in Fabric 1.4.0
		carpet-extra: Carpet Extra 1.4.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.4
		cloth-config2: Cloth Config v4 4.5.6
		durabilityviewer: Giselbaers Durability Viewer 1.16-fabric0.13.1-1.7.2
		easiervillagertrading: EasierVillagerTrading 1.16-fabric0.13.1-1.5.1
		fabric: Fabric API 0.14.0+build.371-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474cb0
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f7c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+e16a9774b0
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c5b0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.0.0+b0993bc102
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.10+059ea86602
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.5+e00ecb5f02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.0+da175ad602
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.2+4d66bed502
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.5+059ea866b0
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.0.1+f362c86e02
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.4+5794386e02
		fabricloader: Fabric Loader 0.8.8+build.202
		gbfabrictools: GBfabrictools 1.2.2+1.16
		inventoryprofiles: Inventory Profiles 0.2.0
		itemscroller: Item Scroller 0.15.0-dev.20200630.022843
		lightoverlay: Light Overlay 5.4.0
		litematica: Litematica 0.0.0-dev.20200630.022912
		lithium: Lithium 0.5.0-rc1
		malilib: MaLiLib 0.10.0-dev.21+arne.1
		minecraft: Minecraft 1.16.1
		minihud: MiniHUD 0.19.0-dev.20200630.023335
		mm: Manningham Mills 2.0
		modmenu: Mod Menu 1.12.2+build.17
		mousewheelie: Mouse Wheelie 1.4.16+mc1.16-rc1
		optifabric: Optifabric 1.1.0-beta2
		org_slf4j_slf4j-api: slf4j-api 1.7.30
		org_slf4j_slf4j-simple: slf4j-simple 1.7.30
		org_zeroturnaround_zt-zip: zt-zip 1.14
		roughlyenoughitems: Roughly Enough Items 4.5.5
		shulkerboxtooltip: Shulker Box Tootip 2.1.0+1.16.1
		tweakeroo: Tweakeroo 0.10.0-dev.20200630.023405
		tweed: Tweed API 3.0.0-beta.9
		voxelmap: VoxelMap 1.10.1
		waila: Hwyla 1.9.22
		worldedit: WorldEdit 7.2.0-beta-01+0eb9ac7
	Player Count: 1 / 8; [class_3222['DancingSnow'/208, l='ServerLevel[测试]', x=-119.70, y=84.00, z=28.19]]
	Data Packs: vanilla (incompatible), fabric/fabric-tool-attribute-api-v1, bbor (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
	OptiFine Version: OptiFine_1.16.1_HD_U_G2_pre2
	OptiFine Build: 20200703-234202
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 451.48
	OpenGlRenderer: GeForce GTX 1060 3GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6
#@!@# Game crashed! Crash report saved to: #@!@# D:\DongJing\Minecraft\MultiMC\instances\1.16.1\.minecraft\crash-reports\crash-2020-07-04_23.41.03-server.txt
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by nokyan** [comment]
Same here.

**Comment by ghost** [comment]
People are reporting that lithium isn't compatible with optifabric.
See:https://github.com/jellysquid3/lithium-fabric/issues/73

**Comment by Miros77** [comment]
thanks
