### ISSUE TITLE
Trying to debug with optifine in development environment

### ISSUE THREAD

**Issue by qouteall** [modmuss50/OptiFabric#52]
I put OptiFine_1.14.4_HD_U_F2 and optiFabric0.4.3 into run/mods folder and added vm option -Doptifabric.extract=true.

`
[12:29:23] [main/WARN]: Error loading class: net/minecraft/class_442 (java.lang.ClassNotFoundException: net/minecraft/class_442)
[12:29:23] [main/WARN]: @Mixin target net.minecraft.class_442 was not found optifabric.mixins.json:MixinTitleScreen
[12:29:23] [main/ERROR]: Error encountered during mixin config postInit step'mixins.mm.json': Failed to setup optifine
java.lang.RuntimeException: Failed to setup optifine
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:31) ~[optifabric-0.2.0.jar:?]
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:261) ~[4a75d3c0-a6db-4998-9fae-b4ed7a1276b3.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:524) ~[sponge-mixin-0.7.11.36.jar:0.7.11.36+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:675) [sponge-mixin-0.7.11.36.jar:0.7.11.36+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) [sponge-mixin-0.7.11.36.jar:0.7.11.36+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) [sponge-mixin-0.7.11.36.jar:0.7.11.36+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) [sponge-mixin-0.7.11.36.jar:0.7.11.36+unknown-b0.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:179) [net.fabricmc.yarn.1_14_4.2.net.fabricmc.fabric-loader-0.4.8+build.157.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:142) [net.fabricmc.yarn.1_14_4.2.net.fabricmc.fabric-loader-0.4.8+build.157.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_181]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:168) [net.fabricmc.yarn.1_14_4.2.net.fabricmc.fabric-loader-0.4.8+build.157.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129) [net.fabricmc.yarn.1_14_4.2.net.fabricmc.fabric-loader-0.4.8+build.157.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [net.fabricmc.yarn.1_14_4.2.net.fabricmc.fabric-loader-0.4.8+build.157.jar:?]
Caused by: java.io.FileNotFoundException: Could not find optifine jar
	at me.modmuss50.optifabric.mod.OptifineVersion.findOptifineJar(OptifineVersion.java:56) ~[optifabric-0.2.0.jar:?]
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:45) ~[optifabric-0.2.0.jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:19) ~[optifabric-0.2.0.jar:?]
	... 12 more
`

**Comment by nikdo3** [comment]
same 4 me

**Comment by modmuss50** [comment]
I will look into making this possible, just putting it in the mods folder will not work, you will need to `modCompile` it. I can see about adding propper instructions for this.

**Comment by mcdj23** [comment]
ya having same problem

**Comment by InitialShoc77** [comment]
ya having the same problem

**Comment by qouteall** [comment]
If implementing it is hard, the next best thing is to show the classes that modified by OptiFine. I used -Doptifabric.extract=true and found the optifine jar in .optifine folder. It has optifine classes remapped, but modified minecraft classes are missing. Fixing this is enough for me. Thank for your efforts.

**Comment by modmuss50** [comment]
Fixed, please read the updated instructions on the github readme.

**Comment by bloncka** [comment]
> Fixed, please read the updated instructions on the github readme
Where can I see it please?
