### ISSUE TITLE
Alright what did I do wrong, "Could not find Optifine jar"

### ISSUE THREAD

**Issue by damian-1** [modmuss50/OptiFabric#67]
![what1](https://user-images.githubusercontent.com/54998632/64450055-4f4fe100-d0af-11e9-805b-b1cd4120f696.jpg)
![what2](https://user-images.githubusercontent.com/54998632/64450061-51b23b00-d0af-11e9-8dd9-be3da0679def.jpg)

"could not find Optifine jar in mods folder", but it is there. Where did I go wrong?

**Comment by rwagnhs** [comment]
I'm having the same problem
![scrot-2613](https://user-images.githubusercontent.com/54223270/64477391-a2ce3780-d160-11e9-969f-d339030e27da.png)

**Comment by rwagnhs** [comment]
I'm having the same problem
```
[11:11:50] [main/ERROR]: Error encountered during mixin config postInit step'mixins.mm.json': Failed to setup optifine
java.lang.RuntimeException: Failed to setup optifine
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:31) ~[optifabric-0.2.0.jar:?]
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:261) ~[526d377f-553b-42c5-8c5a-2cef9594df8d.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:524) ~[sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:675) [sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) [sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) [sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) [sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:180) [fabric-loader-0.6.1+build.165.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) [fabric-loader-0.6.1+build.165.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_212]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:176) [fabric-loader-0.6.1+build.165.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131) [fabric-loader-0.6.1+build.165.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.6.1+build.165.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.io.FileNotFoundException: Could not find optifine jar
	at me.modmuss50.optifabric.mod.OptifineVersion.findOptifineJar(OptifineVersion.java:56) ~[optifabric-0.2.0.jar:?]
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:45) ~[optifabric-0.2.0.jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:19) ~[optifabric-0.2.0.jar:?]
	... 20 more
```
![scrot-2613](https://user-images.githubusercontent.com/54223270/64477406-dc06a780-d160-11e9-884a-73b2ea54cf3c.png)

**Comment by modmuss50** [comment]
Make sure to only have 1 optifine jar, more than one and it wont know what version to load.
