### ISSUE TITLE
Dosen't work with Cauldron Brewing

### ISSUE THREAD

**Issue by GiantNuker** [modmuss50/OptiFabric#68]
Optifine does something to potion colors to make this fail. Idk how else to get potion colors, so I'm asking you to fix this.
```
Exception in thread "Client thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:172)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
    ... 2 more
Caused by: java.lang.NullPointerException
    at net.optifine.Config.isCustomColors(Config.java:1863)
    at net.minecraft.class_1844.method_8055(class_1844.java:123)
    at net.minecraft.class_1844.method_8062(class_1844.java:94)
    at io.github.indicode.fabric.cauldronbrew.recipe.CauldronRecipeManager.getPotionColor(CauldronRecipeManager.java:137)
    at io.github.indicode.fabric.cauldronbrew.fluid.PotionCauldronFluid.<init>(PotionCauldronFluid.java:49)
    at io.github.indicode.fabric.cauldronbrew.recipe.CauldronRecipeManager.getPotionFluid(CauldronRecipeManager.java:62)
    at io.github.indicode.fabric.cauldronbrew.recipe.CauldronRecipeManager.addRecipe(CauldronRecipeManager.java:128)
    at net.minecraft.class_1845.handler$registerCauldron$zfk000(class_1845.java:1019)
    at net.minecraft.class_1845.method_8074(class_1845.java:220)
    at net.minecraft.class_1845.method_8076(class_1845.java:136)
    at net.minecraft.class_2966.method_12851(class_2966.java:49)
    at net.minecraft.class_310.<init>(class_310.java:383)
    at net.minecraft.client.main.Main.main(Main.java:155)
    ... 7 more```

**Comment by modmuss50** [comment]
Can you post a link to the cauldronbrew mod? and explain how I can easily reproduce it, thanks.

**Comment by GiantNuker** [comment]
https://github.com/indi-code/cauldron-brewing
Just run them together

**Comment by GiantNuker** [comment]
heres CF https://www.curseforge.com/minecraft/mc-mods/cauldron-brewing

**Comment by modmuss50** [comment]
thanks, ill take a look at it when I have a chance.

**Comment by liach** [comment]
The problem with optifine is that optifine patches `PotionUtil.getColor(Collection)`, which is actually used on the logical server as well. Optifine did not immediately initialize its color handlers after it injects the patch, causing the crash. My suggested fix is to move the optifine patch so that it does not affect logical servers.

**Comment by modmuss50** [comment]
Closing, the 1.14.4 version is no longer supported.
