### ISSUE TITLE
Batching Chunks

### ISSUE THREAD

**Issue by BorealBlizzard** [modmuss50/OptiFabric#73]
```---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 9/30/19 4:56 PM
Description: Batching chunks

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$EntryIterator.next(Unknown Source)
	at java.util.HashMap$EntryIterator.next(Unknown Source)
	at net.minecraft.class_853.handler$init$zbe000(class_853.java:1045)
	at net.minecraft.class_853.<init>(class_853.java:108)
	at net.minecraft.class_853.generateCache(class_853.java:90)
	at net.minecraft.class_851.createRegionRenderCache(class_851.java:785)
	at net.minecraft.class_851.makeChunkCacheOF(class_851.java:774)
	at net.minecraft.class_851.method_3652(class_851.java:256)
	at net.minecraft.class_845.method_3615(class_845.java:90)
	at net.minecraft.class_845.run(class_845.java:39)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$EntryIterator.next(Unknown Source)
	at java.util.HashMap$EntryIterator.next(Unknown Source)
	at net.minecraft.class_853.handler$init$zbe000(class_853.java:1045)
	at net.minecraft.class_853.<init>(class_853.java:108)
	at net.minecraft.class_853.generateCache(class_853.java:90)
	at net.minecraft.class_851.createRegionRenderCache(class_851.java:785)
	at net.minecraft.class_851.makeChunkCacheOF(class_851.java:774)

-- Affected level --
Details:
	All players: 1 total; [class_746['Boreal_Blizzard'/411240, l='MpServer', x=6876.55, y=71.00, z=-3801.25]]
	Chunk stats: Client Chunk Cache: 729, 119
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-568,71,264), Chunk: (at 8,4,8 in -36,16; contains blocks -576,0,256 to -561,255,271), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Level time: 9312 game time, 50865966 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.14-SNAPSHOT:9e76966:1420) <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:574)
	at net.minecraft.class_310.method_1587(class_310.java:1923)
	at net.minecraft.class_845.run(class_845.java:45)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 667105040 bytes (636 MB) / 2024275968 bytes (1930 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		amecs: Amecs 1.1.2+1.14.4
		blue_endless_jankson: jankson 1.1.0
		cloth: Cloth Events 0.3.1+build.23
		cloth-config2: Cloth Config v2 0.2.0
		fabric: Fabric API 0.3.0+build.200
		fabric-api-base: fabric-api-base 0.1.0+5914746342
		fabric-biomes-v1: fabric-biomes-v1 0.1.0+896c7fbb42
		fabric-commands-v0: fabric-commands-v0 0.1.1+25fd0c5242
		fabric-containers-v0: fabric-containers-v0 0.1.2+25fd0c5242
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+05f11b7542
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.0+5914746342
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.0+ea100f6142
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.0+5914746342
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+1e69a0a542
		fabric-keybindings: fabric-keybindings 0.1.0+93af775a
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.1+7dfef87c42
		fabric-loot-tables-v1: fabric-loot-tables-v1 0.1.0+43028fa642
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+59147463
		fabric-models-v0: fabric-models-v0 0.1.0+5914746342
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+25fd0c5242
		fabric-networking-v0: fabric-networking-v0 0.1.2+ea100f6142
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+592d1d2242
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.2+ea100f6142
		fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.1+9486cfbf42
		fabric-renderer-indigo: fabric-renderer-indigo 0.1.9+9486cfbf42
		fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+02a46d5b42
		fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.0+dc4c57c242
		fabric-rendering-v0: fabric-rendering-v0 0.1.1+6dad974e42
		fabric-resource-loader: fabric-resource-loader 0.1.0+93af775a
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.1+5914746355
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.1+c189dc5c55
		fabric-textures-v0: fabric-textures-v0 0.1.4+792c1c3542
		fabricloader: Fabric Loader 0.4.8+build.157
		mm: Manningham Mills 1.6
		modmenu: Mod Menu 1.6.3+build.101
		mousewheelie: Mouse Wheelie 1.2.7+1.14.4
		net_fabricmc_stitch: stitch 0.2.1.61
		optifabric: Optifabric 0.4.3
		org_slf4j_slf4j-api: slf4j-api 1.7.26
		org_slf4j_slf4j-simple: slf4j-simple 1.7.26
		org_zeroturnaround_zt-zip: zt-zip 1.13
		roughlyenoughitems: Roughly Enough Items 2.9.7+build.143
		tweed: Tweed API 2.2.0-beta.5
		voxelmap: VoxelMap 1.9.13
		waila: Hwyla 1.9.17
	Launched Version: MultiMC5
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Jacob\Desktop\Minecraft\MultiMC\instances\fabric-1.14.4-build.2_yarn-0.4.8-build.157\.minecraft\crash-reports\crash-2019-09-30_16.56.30-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.
```

**Comment by BorealBlizzard** [comment]
I read alot that it had something to do with redstone being in the chunks where you load into, but thats all ik

**Comment by BorealBlizzard** [comment]
Oh, just realized that I have an out of date version, ill try that and see if it fixes.

**Comment by n-aspen** [comment]
Check out #37 they patched it there, update your fabric API version
edit: i was too slow, they figured it out first

**Comment by BorealBlizzard** [comment]
I updated, I was able to load in but after a while I got the same issue.
```---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 9/30/19 4:56 PM
Description: Batching chunks

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$EntryIterator.next(Unknown Source)
	at java.util.HashMap$EntryIterator.next(Unknown Source)
	at net.minecraft.class_853.handler$init$zbe000(class_853.java:1045)
	at net.minecraft.class_853.<init>(class_853.java:108)
	at net.minecraft.class_853.generateCache(class_853.java:90)
	at net.minecraft.class_851.createRegionRenderCache(class_851.java:785)
	at net.minecraft.class_851.makeChunkCacheOF(class_851.java:774)
	at net.minecraft.class_851.method_3652(class_851.java:256)
	at net.minecraft.class_845.method_3615(class_845.java:90)
	at net.minecraft.class_845.run(class_845.java:39)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$EntryIterator.next(Unknown Source)
	at java.util.HashMap$EntryIterator.next(Unknown Source)
	at net.minecraft.class_853.handler$init$zbe000(class_853.java:1045)
	at net.minecraft.class_853.<init>(class_853.java:108)
	at net.minecraft.class_853.generateCache(class_853.java:90)
	at net.minecraft.class_851.createRegionRenderCache(class_851.java:785)
	at net.minecraft.class_851.makeChunkCacheOF(class_851.java:774)

-- Affected level --
Details:
	All players: 1 total; [class_746['Boreal_Blizzard'/411240, l='MpServer', x=6876.55, y=71.00, z=-3801.25]]
	Chunk stats: Client Chunk Cache: 729, 119
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-568,71,264), Chunk: (at 8,4,8 in -36,16; contains blocks -576,0,256 to -561,255,271), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Level time: 9312 game time, 50865966 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.14-SNAPSHOT:9e76966:1420) <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:574)
	at net.minecraft.class_310.method_1587(class_310.java:1923)
	at net.minecraft.class_845.run(class_845.java:45)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 667105040 bytes (636 MB) / 2024275968 bytes (1930 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		amecs: Amecs 1.1.2+1.14.4
		blue_endless_jankson: jankson 1.1.0
		cloth: Cloth Events 0.3.1+build.23
		cloth-config2: Cloth Config v2 0.2.0
		fabric: Fabric API 0.3.0+build.200
		fabric-api-base: fabric-api-base 0.1.0+5914746342
		fabric-biomes-v1: fabric-biomes-v1 0.1.0+896c7fbb42
		fabric-commands-v0: fabric-commands-v0 0.1.1+25fd0c5242
		fabric-containers-v0: fabric-containers-v0 0.1.2+25fd0c5242
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+05f11b7542
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.0+5914746342
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.0+ea100f6142
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.0+5914746342
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+1e69a0a542
		fabric-keybindings: fabric-keybindings 0.1.0+93af775a
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.1+7dfef87c42
		fabric-loot-tables-v1: fabric-loot-tables-v1 0.1.0+43028fa642
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+59147463
		fabric-models-v0: fabric-models-v0 0.1.0+5914746342
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+25fd0c5242
		fabric-networking-v0: fabric-networking-v0 0.1.2+ea100f6142
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+592d1d2242
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.2+ea100f6142
		fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.1+9486cfbf42
		fabric-renderer-indigo: fabric-renderer-indigo 0.1.9+9486cfbf42
		fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+02a46d5b42
		fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.0+dc4c57c242
		fabric-rendering-v0: fabric-rendering-v0 0.1.1+6dad974e42
		fabric-resource-loader: fabric-resource-loader 0.1.0+93af775a
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.1+5914746355
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.1+c189dc5c55
		fabric-textures-v0: fabric-textures-v0 0.1.4+792c1c3542
		fabricloader: Fabric Loader 0.4.8+build.157
		mm: Manningham Mills 1.6
		modmenu: Mod Menu 1.6.3+build.101
		mousewheelie: Mouse Wheelie 1.2.7+1.14.4
		net_fabricmc_stitch: stitch 0.2.1.61
		optifabric: Optifabric 0.4.3
		org_slf4j_slf4j-api: slf4j-api 1.7.26
		org_slf4j_slf4j-simple: slf4j-simple 1.7.26
		org_zeroturnaround_zt-zip: zt-zip 1.13
		roughlyenoughitems: Roughly Enough Items 2.9.7+build.143
		tweed: Tweed API 2.2.0-beta.5
		voxelmap: VoxelMap 1.9.13
		waila: Hwyla 1.9.17
	Launched Version: MultiMC5
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Jacob\Desktop\Minecraft\MultiMC\instances\fabric-1.14.4-build.2_yarn-0.4.8-build.157\.minecraft\crash-reports\crash-2019-09-30_16.56.30-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.
```

**Comment by n-aspen** [comment]
Your still on the same version of fabric api
update here https://www.curseforge.com/minecraft/mc-mods/fabric-api

**Comment by BorealBlizzard** [comment]
> Your still on the same version of fabric api
> update here https://www.curseforge.com/minecraft/mc-mods/fabric-api

k thanks, I thought I did, but maybe i just didnt install it correctly.

**Comment by modmuss50** [comment]
This should be fixed on the latest fabric api, make sure your updated. if it still happens provide a log of it happening on the new version, thanks.
