### ISSUE TITLE
Optifabric Crashes along with other mods

### ISSUE THREAD

**Issue by cinnamonRoll17** [modmuss50/OptiFabric#76]
When Im playing with no mods (except the Voxel map, the mod Menu and the optifabric with the Optifine) in the fabric, it runs right without any problems. The problem appears when I use mods with it, it crashes, sometimes with a crash log, others just sends me an Exit Code -1. Im using Launcher Fenix

I tried removing the optifabric, and the mods works well, but I need the optifine, my pc just doesnt supports minecraft itself and less with mods.

Here is the last Crash Report, there are more reports but I will put just this:

```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 02/10/19 04:11 PM
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:180)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_761.<init>(class_761.java:283)
	at net.minecraft.class_310.method_1503(class_310.java:569)
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:178)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.a.m.main(Unknown Source)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.mm.json:net/minecraft/class_851] from phase [DEFAULT] in config [mixins.mm.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
	... 19 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpected NullPointerException whilst applying the mixin class: null
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:293)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 19 more
Caused by: java.lang.NullPointerException
	at org.spongepowered.asm.lib.ClassReader.<init>(ClassReader.java:162)
	at me.modmuss50.optifabric.patcher.ASMUtils.readClassFromBytes(ASMUtils.java:18)
	at me.modmuss50.optifabric.mod.OptifineInjector.getSourceClassNode(OptifineInjector.java:74)
	at me.modmuss50.optifabric.mod.OptifineInjector.lambda$new$3(OptifineInjector.java:36)
	at com.chocohead.mm.Plugin.preApply(Plugin.java:288)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.preApply(MixinInfo.java:1214)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.preApply(MixinTargetContext.java:1126)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:275)
	... 23 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:180)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_761.<init>(class_761.java:283)
	at net.minecraft.class_310.method_1503(class_310.java:569)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:178)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.a.m.main(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 8.1 (x86) version 6.3
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 266382032 bytes (254 MB) / 536870912 bytes (512 MB) up to 536870912 bytes (512 MB)
	CPUs: 4
	JVM Flags: 10 total; -Xmx512M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+IgnoreUnrecognizedVMOptions -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	Fabric Mods: 
		arcanemagic: Arcane Magic 1.0.0-beta5
		crochet: Crochet 1.1.0
		cutsceneapi: Cutscene API 1.0.0-beta7
		fabric: Fabric API 0.4.0+build.240-1.14
		fabric-api-base: Fabric API Base 0.1.0+2983bc0442
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.0+591e97ae42
		fabric-commands-v0: Fabric Commands (v0) 0.1.1+591e97ae42
		fabric-containers-v0: Fabric Containers (v0) 0.1.2+591e97ae42
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.1+591e97ae42
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.1+591e97ae42
		fabric-dimensions-v1: fabric-dimensions-v1 0.1.0+369ab22e42
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.1.1+591e97ae42
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.1+591e97ae42
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.0+591e97ae42
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+591e97ae42
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.0+591e97ae42
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.0+591e97ae42
		fabric-models-v0: Fabric Models (v0) 0.1.0+591e97ae42
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.0+c877038942
		fabric-networking-v0: Fabric Networking (v0) 0.1.3+591e97ae42
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.1+591e97ae42
		fabric-particles-v1: fabric-particles-v1 0.1.1+c877038942
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.2+591e97ae42
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.1.1+591e97ae42
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.1.13+591e97ae42
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.1+c877038942
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.2+36f27aa342
		fabric-rendering-v0: Fabric Rendering (v0) 0.1.1+591e97ae42
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.3+591e97ae42
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.1+591e97ae42
		fabric-textures-v0: Fabric Textures (v0) 0.1.4+591e97ae42
		fabricloader: Fabric Loader 0.6.2+build.166
		minecraft: Minecraft 1.14.4
		mm: Manningham Mills 1.6
		multiblockapi: MultiBlock API 1.0.1-1
		net_fabricmc_stitch: stitch 0.2.1.61
		optifabric: Optifabric 0.4.0
		org_slf4j_slf4j-api: slf4j-api 1.7.26
		org_slf4j_slf4j-simple: slf4j-simple 1.7.26
		org_zeroturnaround_zt-zip: zt-zip 1.13
		silk: Silk API 1.2.4-43
		sit: Sit 3
		voxelmap: VoxelMap 1.9.13
		wearables: Wearables 0.3.0
	Launched Version: fabric-loader-0.6.2+build.166-1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4276, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/MyTextures
	Current Language: English (US)
	CPU: 4x Intel(R) Celeron(R) CPU N2920 @ 1.86GHz
```

**Comment by modmuss50** [comment]
Can you try updating optifabric, you are using a really old version.

**Comment by Wissotsky** [comment]
Same issue running only optifabric 0.6.0(latest from the curseforge)

**Comment by AdamZGamer** [comment]
Upgrade to Fabric 0.6.4! and it might work (not a pro)

**Comment by modmuss50** [comment]
Closing, the 1.14.4 version is no longer supported.
