### ISSUE TITLE
Unable to launch Minecraft on Fabric 1.14.4 with Optifine HD_U_F4

### ISSUE THREAD

**Issue by itsfood** [modmuss50/OptiFabric#88]
I can't launch my fabric loafer (0.6.4+build.169-1.14.4) with OptiFabric Mod-1.14.4 and OptiFine_1.14.4_HD_U_F4.jar OR ..._F4_MOD.jar. Why is that?

**Comment by modmuss50** [comment]
Can you post the log please?

**Comment by MMAMomma** [comment]
I have the same
17:06:33.543
Cannot offer OpenEye, server returned: 404 Not Found
17:06:37.144
Mixin apply failed mixins.compat.shaders.replaymod.json:MixinShaderRenderChunk -> net.minecraft.class_851: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @Inject annotation on handler$replayModCompat_disableIsPlayerUpdate$zhd000 could not find any targets matching 'isPlayerUpdate' in the target class net.minecraft.class_851. Using refmap mixins.replaymod.refmap.json
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @Inject annotation on handler$replayModCompat_disableIsPlayerUpdate$zhd000 could not find any targets matching 'isPlayerUpdate' in the target class net.minecraft.class_851. Using refmap mixins.replaymod.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:172)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:159)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:151)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:44)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:472)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1180)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:930)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:318)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:281)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:180)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_761.<init>(class_761.java:230)
	at net.minecraft.class_310.method_1503(class_310.java:569)
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:188)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
17:06:37.875
Narrator library for x64 successfully loaded
17:06:51.796
OpenAL initialized.
17:06:51.816
Sound engine started
17:06:52.012
Created: 1024x512 textures-atlas
17:06:53.006
Created: 256x256 textures/particle-atlas
17:06:53.007
Created: 256x256 textures/painting-atlas
17:06:53.008
Created: 256x128 textures/mob_effect-atlas

**Comment by itsfood** [comment]
Yes I can post the log, here it is:
[latest.log](https://github.com/modmuss50/OptiFabric/files/3832264/latest.log)

**Comment by modmuss50** [comment]
Seems to be an issue with the ReplayMod, can you try without that? Or check to see if there is an updated version of it?

**Comment by itsfood** [comment]
I can try it

**Comment by itsfood** [comment]
It's a no go.
[latest.log](https://github.com/modmuss50/OptiFabric/files/3832332/latest.log)

Also ReplayMod is on it's latest version, just downloaded it yesterday.

**Comment by modmuss50** [comment]
With this one you need to update FabricLoader and OptiFabric you are using an older verison of this mod.

**Comment by itsfood** [comment]
I'm pretty sure I just updated last night. I'll look again.

**Comment by itsfood** [comment]
Just double checked, everything is up to date. I'll reinstalled everything, I'll try launching one more time.

**Comment by itsfood** [comment]
Sadly, no avail.
[latest.log](https://github.com/modmuss50/OptiFabric/files/3832397/latest.log)

**Comment by modmuss50** [comment]
@YeetbenderDamB you are using optifabric@0.5.1 when the latest version is optifabric@0.6.0

**Comment by itsfood** [comment]
Ok, I guess most links are outdated then. I’ll try to find the newest version.

**Comment by itsfood** [comment]
Found it! It took me a minute but I got it. Thanks for the help!
