### ISSUE TITLE
Optifine 1.14.4_F4 crashes with Optifabric, F4_pre6 is the last version that worked fine.

### ISSUE THREAD

**Issue by Heitzenberg** [modmuss50/OptiFabric#89]
Here's the crash report:

---- Minecraft Crash Report ----
// Don't do that.

Time: 11.11.19 10:01
Description: Unexpected error

java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class java/util/stream/Stream. Method 'java.util.stream.Stream of(java.lang.Object)' at index 490 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
	at net.minecraft.class_156.method_17815(class_156.java:299)
	at net.minecraft.class_1863.method_17718(class_1863.java:69)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1698)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at net.minecraft.class_1863.method_8132(class_1863.java:69)
	at fi.dy.masa.itemscroller.util.InventoryUtils.onSlotChangedCraftingGrid(InventoryUtils.java:67)
	at net.minecraft.class_1714.handler$onUpdateResult$zhb000(class_1714.java:534)
	at net.minecraft.class_1714.method_17399(class_1714.java:61)
	at net.minecraft.class_1723.method_7609(class_1723.java:131)
	at net.minecraft.class_1715.method_5447(class_1715.java:70)
	at net.minecraft.class_1735.method_7673(class_1735.java:80)
	at net.minecraft.class_1703.method_7610(class_1703.java:465)
	at net.minecraft.class_634.method_11153(class_634.java:1122)
	at net.minecraft.class_2649.method_11439(class_2649.java:49)
	at net.minecraft.class_2649.method_11054(class_2649.java:12)
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:33)
	at net.minecraft.class_1255.method_18859(class_1255.java:170)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:135)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:915)
	at net.minecraft.class_310.method_1514(class_310.java:410)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:188)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.class_156.method_17815(class_156.java:299)
	at net.minecraft.class_1863.method_17718(class_1863.java:69)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1698)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at net.minecraft.class_1863.method_8132(class_1863.java:69)
	at fi.dy.masa.itemscroller.util.InventoryUtils.onSlotChangedCraftingGrid(InventoryUtils.java:67)
	at net.minecraft.class_1714.handler$onUpdateResult$zhb000(class_1714.java:534)
	at net.minecraft.class_1714.method_17399(class_1714.java:61)
	at net.minecraft.class_1723.method_7609(class_1723.java:131)
	at net.minecraft.class_1715.method_5447(class_1715.java:70)
	at net.minecraft.class_1735.method_7673(class_1735.java:80)
	at net.minecraft.class_1703.method_7610(class_1703.java:465)
	at net.minecraft.class_634.method_11153(class_634.java:1122)
	at net.minecraft.class_2649.method_11439(class_2649.java:49)
	at net.minecraft.class_2649.method_11054(class_2649.java:12)
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:33)
	at net.minecraft.class_1255.method_18859(class_1255.java:170)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:135)

-- Affected level --
Details:
	All players: 1 total; [class_746['Heitzenberg'/121, l='MpServer', x=332.57, y=56.00, z=589.51]]
	Chunk stats: Client Chunk Cache: 729, 140
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (515,97,460), Chunk: (at 3,6,12 in 32,28; contains blocks 512,0,448 to 527,255,463), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Level time: 20416608 game time, 1000 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:574)
	at net.minecraft.class_310.method_1587(class_310.java:1923)
	at net.minecraft.class_310.method_1514(class_310.java:430)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:188)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 13.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 420165080 bytes (400 MB) / 1291845632 bytes (1232 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 12
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:ParallelGCThreads=6 -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	Launched Version: fabric-loader-0.6.4+build.169-1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 440.97, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Faithful_1.14.4-r4.2.zip, file/Faithful textures 1.14.zip, file/Simple Item Frames - Faithful.zip, file/bob_ross_paintings_pack.zip, file/Save Diamond Tools v1.1.zip, file/ShieldCorrections.zip, file/No Pumpkin Blur 1.9+.zip, file/Quieter Ghasts.zip, file/VanillaTweaks_RedstonePowerLevel.zip, file/Lively Default - Custom Sky.zip
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 1600X Six-Core Processor 
	OptiFine Version: OptiFine_1.14.4_HD_U_F4
	OptiFine Build: 20191023-123115
	Render Distance Chunks: 12
	Mipmaps: 2
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 440.97
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by modmuss50** [comment]
Im not able to repoduce this in dev, I do see itemscroller in the stacktrace can you try without that mod to see if thats the issue?

**Comment by Heitzenberg** [comment]
Indeed, it's working fine without ItemScroller. I guess I have to report the bug over there, then.

**Comment by Heitzenberg** [comment]
Even without ItemScroller, the game crashes as soon as I try to craft something.

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 11.11.19 15:50
Description: Exception in server tick loop

java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class java/util/stream/Stream. Method 'java.util.stream.Stream of(java.lang.Object)' at index 490 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
	at net.minecraft.class_156.method_17815(class_156.java:299)
	at net.minecraft.class_1863.method_17718(class_1863.java:69)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:302)
	at com.google.common.collect.CollectSpliterators$1WithCharacteristics.tryAdvance(CollectSpliterators.java:60)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at net.minecraft.class_1863.method_8132(class_1863.java:69)
	at net.minecraft.class_1714.method_17399(class_1714.java:66)
	at net.minecraft.class_1714.method_17401(class_1714.java:80)
	at net.minecraft.class_3914.method_17394(class_3914.java:35)
	at net.minecraft.class_3914$2.method_17395(class_3914.java:22)
	at net.minecraft.class_3914.method_17393(class_3914.java:34)
	at net.minecraft.class_1714.method_7609(class_1714.java:80)
	at net.minecraft.class_1715.method_5447(class_1715.java:70)
	at net.minecraft.class_1735.method_7673(class_1735.java:80)
	at net.minecraft.class_1703.method_7593(class_1703.java:218)
	at net.minecraft.class_3244.method_12076(class_3244.java:1227)
	at net.minecraft.class_2813.method_12191(class_2813.java:33)
	at net.minecraft.class_2813.method_11054(class_2813.java:10)
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:33)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:170)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:135)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:712)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:706)
	at net.minecraft.class_1255.method_18857(class_1255.java:148)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:691)
	at net.minecraft.server.MinecraftServer.handler$modifiedRunLoop$zbd000(MinecraftServer.java:2833)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:621)
	at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by modmuss50** [comment]
Humm, I will take another look then. Can you post your full mod list?

**Comment by Heitzenberg** [comment]
Thanks for looking into it! I'm using:

fabric-carpet-1.14.4-1.2.1+v191030
itemscroller-fabric-1.14.4-0.15.0-dev.20190720.190250
litematica-fabric-1.14.4-0.0.0-dev.20190720.191654
malilib-fabric-1.14.4-0.10.0-dev.20
minihud-fabric-1.14.4-0.19.0-dev.20191007.003640
modmenu-1.7.15.1.14.4+build.127
optifabric-0.6.0 + Optifine of course
shulkerboxtooltip-1.3.1+1.14.4

**Comment by Heitzenberg** [comment]
Any news on this?

**Comment by josephrooks** [comment]
@Heitzenberg Probably not related, but if you're using MiniHUD why are you using Shulker Box Tooltip?

**Comment by Heitzenberg** [comment]
The way MiniHUD displays the contents of the shulker box is not perfect, at least for me. It often gets cut off on the edges of the screen.

**Comment by Heitzenberg** [comment]
With the latest Fabric loader version (0.7.0-build171) I get the same crash as soon as the client loads, no matter the Optifine version.

**Comment by Heitzenberg** [comment]
Optifabric 0.7.0 with Fabric 0.7.0-build171 still crashes with Optifine_F4, with the pre6 version of Optifine_F4, everything is working.

**Comment by Heitzenberg** [comment]
Optifabric 0.7.0 with Fabric 0.7.0-build171 is working fine with Optifine_F5 that got released yesterday, so this issue is resolved I guess.

**Comment by imapancake22** [comment]
> Optifabric 0.7.0 with Fabric 0.7.0-build171 is working fine with Optifine_F5 that got released yesterday, so this issue is resolved I guess.

R u using multimc because when I go to the vanilla download thing I can go up to 0.5.2

**Comment by Heitzenberg** [comment]
No, I'm using the 0.5.x vanilla installer, which creates the Fabric 0.7.x profile.
