### ISSUE TITLE
Openig with multiMC, fabric API, OptiFabric, OptiFine and does not work in 1.14.4

### ISSUE THREAD

**Issue by ThurWander** [modmuss50/OptiFabric#91]
i don't know much about it, but it keeps saying null...

**Comment by Frontear** [comment]
Post your logs, otherwise we really can't help you

**Comment by ThurWander** [comment]
MultiMC version: 0.6.7-1375


Minecraft folder is:
C:/Users/Usuario/Downloads/MultiMC/instances/multimc/.minecraft


Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe


Java is version 1.8.0_221, using 32-bit architecture.


Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.


Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  C:/Users/Usuario/Downloads/MultiMC/instances/multimc/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/Usuario/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/net/fabricmc/intermediary/1.14.4/intermediary-1.14.4.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.2.0.11/tiny-mappings-parser-0.2.0.11.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/net/fabricmc/sponge-mixin/0.7.11.38/sponge-mixin-0.7.11.38.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/net/fabricmc/tiny-remapper/0.2.0.52/tiny-remapper-0.2.0.52.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/org/ow2/asm/asm/7.1/asm-7.1.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/org/ow2/asm/asm-analysis/7.1/asm-analysis-7.1.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/org/ow2/asm/asm-commons/7.1/asm-commons-7.1.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/org/ow2/asm/asm-tree/7.1/asm-tree-7.1.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/org/ow2/asm/asm-util/7.1/asm-util-7.1.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/net/fabricmc/fabric-loader/0.6.4+build.169/fabric-loader-0.6.4+build.169.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/com/mojang/minecraft/1.14.4/minecraft-1.14.4-client.jar

Native libraries:
  C:/Users/Usuario/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/Usuario/Downloads/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] fabric-api-0.4.1+build.245-1.14
  [✔️] First-person-Model-Mod-Fabric-1.14.4
  [✔️] launchwrapper-of-2.1
  [✔️] Mambience-0.6.1
  [✔️] optifabric_1.14.4_0.4.3
  [❌] OptiFine_1.14.4_HD_U_F4.jar (disabled)
  [✔️] OptiFine_1.14.4_HD_U_F4_MOD
  [✔️] orderly-1.1.2+build.19
  [✔️] ToroCrafts-Damage-Indicators-Mod-Fabric-1.14.4

Params:
  --username  --version MultiMC5 --gameDir C:/Users/Usuario/Downloads/MultiMC/instances/multimc/.minecraft --assetsDir C:/Users/Usuario/Downloads/MultiMC/assets --assetIndex 1.14 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 12096


Using onesix launcher.

[16:36:22] [main/INFO]: Loading for game Minecraft 1.14.4
[16:36:24] [main/WARN]: Mod `mm` (1.6) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[16:36:24] [main/WARN]: Mod `optifabric` (0.4.3) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[16:36:24] [main/INFO]: [FabricLoader] Loading 41 mods: minecraft@1.14.4, fabric-networking-blockentity-v0@0.2.0+c877038942, fabric-renderer-api-v1@0.1.1+591e97ae42, fabric-keybindings-v0@0.1.1+591e97ae42, mambience@0.6.1, fabricloader@0.6.4+build.169, org_zeroturnaround_zt-zip@1.13, fabric-renderer-indigo@0.1.13+591e97ae42, firstperson@1.0.1, fabric-containers-v0@0.1.2+591e97ae42, fabric-dimensions-v1@0.1.0+369ab22e42, fabric-biomes-v1@0.1.0+591e97ae42, org_slf4j_slf4j-simple@1.7.26, fabric-events-interaction-v0@0.1.1+591e97ae42, fabric-crash-report-info-v1@0.1.1+591e97ae42, torohealth@1.14.4-fabric-2, net_fabricmc_stitch@0.2.1.61, orderly@1.1.2+build.19, fabric-api-base@0.1.1+2ac73e7242, fabric-rendering-v0@0.1.1+591e97ae42, cloth-config2@1.1.1, fabric-rendering-data-attachment-v1@0.1.1+c877038942, mm@1.6, fabric-resource-loader-v0@0.1.3+591e97ae42, fabric-textures-v0@0.1.4+591e97ae42, fabric-content-registries-v0@0.1.1+591e97ae42, fabric-tag-extensions-v0@0.1.1+591e97ae42, optifabric@0.4.3, fabric-rendering-fluids-v1@0.1.2+36f27aa342, fabric-registry-sync-v0@0.2.2+591e97ae42, fabric-commands-v0@0.1.1+591e97ae42, fabric-mining-levels-v0@0.1.0+591e97ae42, fabric-events-lifecycle-v0@0.1.1+591e97ae42, fabric-loot-tables-v1@0.1.0+591e97ae42, org_slf4j_slf4j-api@1.7.26, fabric@0.4.1+build.245-1.14, fabric-models-v0@0.1.0+591e97ae42, fabric-particles-v1@0.1.1+c877038942, fabric-item-groups-v0@0.1.0+591e97ae42, fabric-object-builders-v0@0.1.1+591e97ae42, fabric-networking-v0@0.1.3+591e97ae42
[16:36:24] [main/WARN]: Mod `net_fabricmc_stitch` (0.2.1.61) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[16:36:24] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/Usuario/Downloads/MultiMC/libraries/net/fabricmc/sponge-mixin/0.7.11.38/sponge-mixin-0.7.11.38.jar Service=Knot/Fabric Env=CLIENT
[16:36:25] [main/INFO]: Compatibility level set to JAVA_8
Setting up optifine for the first time, this may take a few seconds.
Building lambada fix mappings
[16:36:25] [main/ERROR]: Error encountered during mixin config postInit step'mixins.mm.json': Failed to setup optifine
java.lang.RuntimeException: Failed to setup optifine
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:37) ~[optifabric_1.14.4_0.4.3.jar:?]
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:289) ~[9750e9dc-ac59-432f-abcf-7218d6259cb9.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:524) ~[sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:675) [sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) [sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) [sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) [sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:180) [fabric-loader-0.6.4+build.169.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) [fabric-loader-0.6.4+build.169.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_221]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:186) [fabric-loader-0.6.4+build.169.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131) [fabric-loader-0.6.4+build.169.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.6.4+build.169.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at java.util.jar.JarFile.getInputStream(Unknown Source) ~[?:1.8.0_221]
	at me.modmuss50.optifabric.patcher.ASMUtils.asClassNode(ASMUtils.java:30) ~[optifabric_1.14.4_0.4.3.jar:?]
	at me.modmuss50.optifabric.patcher.LambadaRebuiler.buildClassMap(LambadaRebuiler.java:57) ~[optifabric_1.14.4_0.4.3.jar:?]
	at me.modmuss50.optifabric.patcher.LambadaRebuiler.buildLambadaMap(LambadaRebuiler.java:38) ~[optifabric_1.14.4_0.4.3.jar:?]
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:85) ~[optifabric_1.14.4_0.4.3.jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:25) ~[optifabric_1.14.4_0.4.3.jar:?]
	... 20 more
[16:36:25] [main/INFO]: Setting user: Thur_Wander
[16:36:29] [main/INFO]: [STDOUT]: Loaded FirstPerson Models
[16:36:29] [main/INFO]: Definitely not up to no good
[16:36:29] [main/INFO]: [Indigo] Registering Indigo renderer!
[16:36:29] [main/INFO]: [Indigo] Compatibility mode enabled.
[16:36:29] [main/WARN]: Skipping bad option: lastServer:
[16:36:29] [main/INFO]: LWJGL Version: 3.2.2 build 10
[16:36:31] [main/INFO]: Narrator library for x86 successfully loaded
[16:36:32] [Server-Worker-1/WARN]: File minecraft:sounds/ambient/cave/wood3.ogg does not exist, cannot add it to event minecraft:cave.wood
[16:36:40] [main/INFO]: OpenAL initialized.
[16:36:40] [main/INFO]: Sound engine started
[16:36:41] [main/INFO]: Created: 1024x512 textures-atlas
[16:36:41] [main/INFO]: Created: 256x256 textures/particle-atlas
[16:36:41] [main/INFO]: Created: 256x256 textures/painting-atlas
[16:36:41] [main/INFO]: Created: 256x128 textures/mob_effect-atlas
[16:36:44] [main/INFO]: Stopping!
Process exited with code 0.

is this ok?

**Comment by isaiahshiner** [comment]
I get the exact same error, except with 1.8.0_231, 64 bit java.

[Error Log](https://pastebin.com/raw/kypPmNuV)

**Comment by lunananananananana** [comment]
I didn't check if it's the same error, but I'm getting a similar error on Manjaro (Linux) with OpenJDK build 1.8.0_232-b09, also 64 bit

**Comment by lunananananananana** [comment]
Looking at #92, Fabric 0.7.0 isn't supported yet, use 0.6.4 instead

**Comment by isaiahshiner** [comment]
Switching to 0.6.4 worked, thank you!

**Comment by AdamZGamer** [comment]
getting the error help!

**Comment by isaiahshiner** [comment]
@AdamHafez 
In Multi-MC
1. Select the instance with optifabric
2. Edit Instance (on the right side)
3. Version (Tab on the left)
4. Fabric Loader
5. Change version (in the upper right)
6. 0.6.4+build.170
7. Profit!
