### ISSUE TITLE
failed to setup Optifine (1.14.4)

### ISSUE THREAD

**Issue by LetMeComplain** [modmuss50/OptiFabric#93]
MultiMC version: 0.6.7-1375

Minecraft folder is:
C:/Users/Shame/Desktop/MultiMC/instances/1.14.41/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_231, using 64-bit architecture.

Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  C:/Users/Shame/Desktop/MultiMC/instances/1.14.41/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/Shame/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/net/fabricmc/intermediary/1.14.4/intermediary-1.14.4.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.2.0.11/tiny-mappings-parser-0.2.0.11.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8+build.16/sponge-mixin-0.8+build.16.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/net/fabricmc/tiny-remapper/0.2.0.52/tiny-remapper-0.2.0.52.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/org/ow2/asm/asm/7.2/asm-7.2.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/org/ow2/asm/asm-analysis/7.2/asm-analysis-7.2.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/org/ow2/asm/asm-commons/7.2/asm-commons-7.2.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/org/ow2/asm/asm-tree/7.2/asm-tree-7.2.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/org/ow2/asm/asm-util/7.2/asm-util-7.2.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/net/fabricmc/fabric-loader/0.7.0+build.171/fabric-loader-0.7.0+build.171.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/com/mojang/minecraft/1.14.4/minecraft-1.14.4-client.jar

Native libraries:
  C:/Users/Shame/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/Shame/Desktop/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] fabric-api-0.3.2+build.226-1.14
  [✔️] fabricmod_VoxelMap-1.9.13_for_1.14.4
  [✔️] horse-stats-vanilla-1.0.1
  [✔️] modmenu-1.7.14.1.14.4+build.126
  [✔️] optifabric-0.5.2
  [✔️] OptiFine_1.14.4_HD_U_F3_MOD
  [✔️] togglewalk-1.1.0

Params:
  --username  --version MultiMC5 --gameDir C:/Users/Shame/Desktop/MultiMC/instances/1.14.41/.minecraft --assetsDir C:/Users/Shame/Desktop/MultiMC/assets --assetIndex 1.14 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 2808

Using onesix launcher.

[01:45:36] [main/INFO]: Loading for game Minecraft 1.14.4
[01:45:39] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-resource-loader-v0: used 0.1.3+591e97ae42, also found 0.1.3+b02deb0042
[01:45:39] [main/WARN]: Mod `extracraftx_togglewalk` (1.1.0) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[01:45:39] [main/WARN]: Mod `mm` (1.6) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[01:45:39] [main/WARN]: Mod `voxelmap` (1.9.13) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[01:45:39] [main/INFO]: [FabricLoader] Loading 38 mods: minecraft@1.14.4, fabric-networking-blockentity-v0@0.1.1+591e97ae42, fabric-renderer-api-v1@0.1.1+591e97ae42, fabric-keybindings-v0@0.1.1+591e97ae42, horsestatsvanilla@1.0.1, modmenu@1.7.14.1.14.4+build.126, fabricloader@0.7.0+build.171, org_zeroturnaround_zt-zip@1.13, fabric-renderer-indigo@0.1.13+591e97ae42, extracraftx_togglewalk@1.1.0, fabric-containers-v0@0.1.2+591e97ae42, fabric-biomes-v1@0.1.0+591e97ae42, org_slf4j_slf4j-simple@1.7.26, fabric-crash-report-info-v1@0.1.1+591e97ae42, fabric-events-interaction-v0@0.1.1+591e97ae42, net_fabricmc_stitch@0.2.1.61, fabric-api-base@0.1.0+2983bc0442, fabric-rendering-v0@0.1.1+591e97ae42, mm@1.6, fabric-rendering-data-attachment-v1@0.1.0+591e97ae42, fabric-resource-loader-v0@0.1.3+591e97ae42, fabric-textures-v0@0.1.4+591e97ae42, fabric-content-registries-v0@0.1.1+591e97ae42, fabric-tag-extensions-v0@0.1.1+591e97ae42, optifabric@0.5.2, fabric-rendering-fluids-v1@0.1.2+36f27aa342, fabric-commands-v0@0.1.1+591e97ae42, fabric-registry-sync-v0@0.2.2+591e97ae42, fabric-mining-levels-v0@0.1.0+591e97ae42, voxelmap@1.9.13, fabric-events-lifecycle-v0@0.1.1+591e97ae42, fabric-loot-tables-v1@0.1.0+591e97ae42, fabric@0.3.2+build.226-1.14, org_slf4j_slf4j-api@1.7.26, fabric-item-groups-v0@0.1.0+591e97ae42, fabric-models-v0@0.1.0+591e97ae42, fabric-object-builders-v0@0.1.1+591e97ae42, fabric-networking-v0@0.1.3+591e97ae42
[01:45:39] [main/WARN]: Mod `modmenu` (1.7.14.1.14.4+build.126) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[01:45:39] [main/WARN]: Mod `net_fabricmc_stitch` (0.2.1.61) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[01:45:39] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/Shame/Desktop/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8+build.16/sponge-mixin-0.8+build.16.jar Service=Knot/Fabric Env=CLIENT
[01:45:40] [main/ERROR]: Error encountered during mixin config postInit step'mixins.mm.json': Failed to setup optifine
java.lang.RuntimeException: Failed to setup optifine
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:37) ~[optifabric-0.5.2.jar:?]
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:289) ~[c7ea3055-9edc-48fe-9ed9-0b050d7fd9a6.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128) ~[sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:665) ~[sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:512) [sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:409) [sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:385) [sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:280) [sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.7.0+build.171.jar:0.8+build.16+unknown-b16.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174) [fabric-loader-0.7.0+build.171.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) [fabric-loader-0.7.0+build.171.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_231]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:186) [fabric-loader-0.7.0+build.171.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138) [fabric-loader-0.7.0+build.171.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.7.0+build.171.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: org/spongepowered/asm/lib/ClassWriter
	at me.modmuss50.optifabric.mod.OptifineVersion.getJarType(OptifineVersion.java:66) ~[optifabric-0.5.2.jar:?]
	at me.modmuss50.optifabric.mod.OptifineVersion.findOptifineJar(OptifineVersion.java:35) ~[optifabric-0.5.2.jar:?]
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:46) ~[optifabric-0.5.2.jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:25) ~[optifabric-0.5.2.jar:?]
	... 24 more
Caused by: java.lang.ClassNotFoundException: org.spongepowered.asm.lib.ClassWriter
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_231]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161) ~[fabric-loader-0.7.0+build.171.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
	at me.modmuss50.optifabric.mod.OptifineVersion.getJarType(OptifineVersion.java:66) ~[optifabric-0.5.2.jar:?]
	at me.modmuss50.optifabric.mod.OptifineVersion.findOptifineJar(OptifineVersion.java:35) ~[optifabric-0.5.2.jar:?]
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:46) ~[optifabric-0.5.2.jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:25) ~[optifabric-0.5.2.jar:?]
	... 24 more
java.lang.NoSuchMethodError: org.spongepowered.asm.mixin.transformer.ext.ITargetClassContext.getClassNode()Lorg/spongepowered/asm/lib/tree/ClassNode;
	at com.chocohead.mm.Extension.postApply(Extension.java:30)
	at org.spongepowered.asm.mixin.transformer.ext.Extensions.postApply(Extensions.java:167)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:344)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:188)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:190)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:188)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:357)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.client.main.Main.main(Main.java:155)
	... 15 more
Caused by: java.lang.NoSuchMethodError: org.spongepowered.asm.mixin.transformer.ext.ITargetClassContext.getClassNode()Lorg/spongepowered/asm/lib/tree/ClassNode;
	at com.chocohead.mm.Extension.postApply(Extension.java:30)
	at org.spongepowered.asm.mixin.transformer.ext.Extensions.postApply(Extensions.java:167)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:344)
	... 22 more
Exiting with -1
2019-11-19 01:45:40,696 Client Shutdown Thread WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
java.lang.NoSuchMethodError: org.spongepowered.asm.mixin.transformer.ext.ITargetClassContext.getClassNode()Lorg/spongepowered/asm/lib/tree/ClassNode;
	at com.chocohead.mm.Extension.postApply(Extension.java:30)
	at org.spongepowered.asm.mixin.transformer.ext.Extensions.postApply(Extensions.java:167)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:344)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.client.main.Main$2.run(Main.java:138)
Process exited with code -1.

**Comment by AdamZGamer** [comment]
same thing happened 2 me and im stuck cant fix it

**Comment by Frontear** [comment]
Your fabric-loader is too new, Optifabric has yet to support it as per #92. Downgrade to 0.6.4.

**Comment by modmuss50** [comment]
Fixed please update to this version: https://github.com/modmuss50/OptiFabric/releases/tag/0.7.0
