### ISSUE TITLE
The game crashes after it launches

### ISSUE THREAD

**Issue by AdamZGamer** [modmuss50/OptiFabric#94]
i got this error:
[14:24:52] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
[14:24:52] [main/WARN]: Error loading class: net/optifine/shaders/ShadersRender (java.lang.ClassNotFoundException: net/optifine/shaders/ShadersRender)
[14:24:52] [main/ERROR]: Error encountered during mixin config postInit step'mixins.mm.json': Failed to setup optifine
java.lang.RuntimeException: Failed to setup optifine
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:40) ~[optifabric-0.6.0%20(1).jar:?]
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:289) ~[374f1b5b-2877-40f0-9faf-52ad02c0e069.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128) ~[sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:665) ~[sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:512) [sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:409) [sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:385) [sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:280) [sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.8+build.16.jar:0.8+build.16+unknown-b16.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.7.0+build.171.jar:0.8+build.16+unknown-b16.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174) [fabric-loader-0.7.0+build.171.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) [fabric-loader-0.7.0+build.171.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:186) [fabric-loader-0.7.0+build.171.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138) [fabric-loader-0.7.0+build.171.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.7.0+build.171.jar:?]
Caused by: java.lang.NoClassDefFoundError: org/spongepowered/asm/lib/ClassWriter
	at me.modmuss50.optifabric.mod.OptifineVersion.getJarType(OptifineVersion.java:66) ~[optifabric-0.6.0%20(1).jar:?]
	at me.modmuss50.optifabric.mod.OptifineVersion.findOptifineJar(OptifineVersion.java:35) ~[optifabric-0.6.0%20(1).jar:?]
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:49) ~[optifabric-0.6.0%20(1).jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:28) ~[optifabric-0.6.0%20(1).jar:?]
	... 16 more
Caused by: java.lang.ClassNotFoundException: org.spongepowered.asm.lib.ClassWriter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161) ~[fabric-loader-0.7.0+build.171.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at me.modmuss50.optifabric.mod.OptifineVersion.getJarType(OptifineVersion.java:66) ~[optifabric-0.6.0%20(1).jar:?]
	at me.modmuss50.optifabric.mod.OptifineVersion.findOptifineJar(OptifineVersion.java:35) ~[optifabric-0.6.0%20(1).jar:?]
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:49) ~[optifabric-0.6.0%20(1).jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:28) ~[optifabric-0.6.0%20(1).jar:?]
	... 16 more
and tried it on MultiMC
same error happened plz help!

**Comment by Frontear** [comment]
Your fabric-loader is too new, Optifabric has yet to support it as per #92. Downgrade to 0.6.4.

**Comment by AdamZGamer** [comment]
thx

**Comment by modmuss50** [comment]
Fixed please update to this version: https://github.com/modmuss50/OptiFabric/releases/tag/0.7.0
