### ISSUE TITLE
Optifabric issues

### ISSUE THREAD

**Issue by olvanyr** [modmuss50/OptiFabric#95]
Hello ! I have tried to use optifabric for a little time now, and I already downgrade to 0.6.4
( I have tried with different version of optifine and optifabric)

there is my  log : 

MultiMC version: 0.6.7-1375

Minecraft folder is:
C:/Users/ilona/OneDrive/Bureau/MultiMC/instances/optifabric/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Version de Java 1.8.0_201, utilisant une architecture 64-bit .

Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  C:/Users/ilona/OneDrive/Bureau/MultiMC/instances/optifabric/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/net/fabricmc/intermediary/1.14.4/intermediary-1.14.4.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.2.0.11/tiny-mappings-parser-0.2.0.11.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/net/fabricmc/sponge-mixin/0.7.11.38/sponge-mixin-0.7.11.38.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/net/fabricmc/tiny-remapper/0.2.0.52/tiny-remapper-0.2.0.52.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/org/ow2/asm/asm/7.1/asm-7.1.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/org/ow2/asm/asm-analysis/7.1/asm-analysis-7.1.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/org/ow2/asm/asm-commons/7.1/asm-commons-7.1.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/org/ow2/asm/asm-tree/7.1/asm-tree-7.1.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/org/ow2/asm/asm-util/7.1/asm-util-7.1.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/net/fabricmc/fabric-loader/0.6.4+build.170/fabric-loader-0.6.4+build.170.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/com/mojang/minecraft/1.14.4/minecraft-1.14.4-client.jar

Native libraries:
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] fabric-api-0.4.1+build.245-1.14
  [✔️] optifabric-0.4.3
  [✔️] OptiFine_1.14.4_HD_U_F2_MOD
  [✔️] RoughlyEnoughItems-3.2.8+build.51

Params:
  --username  --version MultiMC5 --gameDir C:/Users/ilona/OneDrive/Bureau/MultiMC/instances/optifabric/.minecraft --assetsDir C:/Users/ilona/OneDrive/Bureau/MultiMC/assets --assetIndex 1.14 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms4480m, -Xmx7913m, -Duser.language=en]

ID du processus Minecraft: 16844

Using onesix launcher.

[23:52:10] [main/INFO]: Loading for game Minecraft 1.14.4
[23:52:12] [main/WARN]: Mod `mm` (1.6) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[23:52:12] [main/WARN]: Mod `optifabric` (0.4.3) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[23:52:12] [main/WARN]: Mod `cloth` (0.6.0) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[23:52:12] [main/INFO]: [FabricLoader] Loading 41 mods: minecraft@1.14.4, fabric-renderer-api-v1@0.1.1+591e97ae42, fabric-networking-blockentity-v0@0.2.0+c877038942, fabric-keybindings-v0@0.1.1+591e97ae42, fabricloader@0.6.4+build.170, org_zeroturnaround_zt-zip@1.13, fabric-renderer-indigo@0.1.13+591e97ae42, fabric-containers-v0@0.1.2+591e97ae42, fiber2cloth@1.2.1, fabric-dimensions-v1@0.1.0+369ab22e42, fabric-biomes-v1@0.1.0+591e97ae42, roughlyenoughitems@3.2.8+build.51, org_slf4j_slf4j-simple@1.7.26, fabric-crash-report-info-v1@0.1.1+591e97ae42, fabric-events-interaction-v0@0.1.1+591e97ae42, net_fabricmc_stitch@0.2.1.61, fabric-api-base@0.1.1+2ac73e7242, fabric-rendering-v0@0.1.1+591e97ae42, cloth-config2@1.7.3, fabric-rendering-data-attachment-v1@0.1.1+c877038942, mm@1.6, fabric-resource-loader-v0@0.1.3+591e97ae42, me_zeroeightsix_fiber@0.6.0-7, fabric-textures-v0@0.1.4+591e97ae42, fabric-content-registries-v0@0.1.1+591e97ae42, fabric-tag-extensions-v0@0.1.1+591e97ae42, optifabric@0.4.3, fabric-rendering-fluids-v1@0.1.2+36f27aa342, fabric-commands-v0@0.1.1+591e97ae42, fabric-registry-sync-v0@0.2.2+591e97ae42, fabric-mining-levels-v0@0.1.0+591e97ae42, fabric-loot-tables-v1@0.1.0+591e97ae42, fabric-events-lifecycle-v0@0.1.1+591e97ae42, fabric@0.4.1+build.245-1.14, org_slf4j_slf4j-api@1.7.26, fabric-particles-v1@0.1.1+c877038942, fabric-models-v0@0.1.0+591e97ae42, fabric-item-groups-v0@0.1.0+591e97ae42, fabric-networking-v0@0.1.3+591e97ae42, fabric-object-builders-v0@0.1.1+591e97ae42, cloth@0.6.0
[23:52:12] [main/WARN]: Mod `net_fabricmc_stitch` (0.2.1.61) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[23:52:12] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/ilona/OneDrive/Bureau/MultiMC/libraries/net/fabricmc/sponge-mixin/0.7.11.38/sponge-mixin-0.7.11.38.jar Service=Knot/Fabric Env=CLIENT
[23:52:13] [main/INFO]: Compatibility level set to JAVA_8
Setting up optifine for the first time, this may take a few seconds.
Building lambada fix mappings
Remapping optifine with fixed lambada names
[23:52:15] [main/ERROR]: Error encountered during mixin config postInit step'mixins.mm.json': Failed to setup optifine
java.lang.RuntimeException: Failed to setup optifine
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:37) ~[optifabric-0.4.3.jar:?]
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:289) ~[1088da56-96ae-4277-96d8-54acf805ca4c.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:524) ~[sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:675) [sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) [sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) [sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) [sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:180) [fabric-loader-0.6.4+build.170.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) [fabric-loader-0.6.4+build.170.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_201]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:186) [fabric-loader-0.6.4+build.170.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138) [fabric-loader-0.6.4+build.170.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.6.4+build.170.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.AbstractMethodError: me.modmuss50.optifabric.patcher.LambadaRebuiler.load(Lnet/fabricmc/tinyremapper/IMappingProvider$MappingAcceptor;)V
	at net.fabricmc.tinyremapper.TinyRemapper.loadMappings(TinyRemapper.java:428) ~[tiny-remapper-0.2.0.52.jar:0.2.0.52]
	at net.fabricmc.tinyremapper.TinyRemapper.refresh(TinyRemapper.java:656) ~[tiny-remapper-0.2.0.52.jar:0.2.0.52]
	at net.fabricmc.tinyremapper.TinyRemapper.apply(TinyRemapper.java:606) ~[tiny-remapper-0.2.0.52.jar:0.2.0.52]
	at me.modmuss50.optifabric.patcher.RemapUtils.mapJar(RemapUtils.java:38) ~[optifabric-0.4.3.jar:?]
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:89) ~[optifabric-0.4.3.jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:25) ~[optifabric-0.4.3.jar:?]
	... 20 more
[23:52:15] [main/INFO]: Setting user: olvanyr27
[23:52:18] [main/INFO]: Definitely not up to no good
[23:52:18] [main/INFO]: [Indigo] Registering Indigo renderer!
[23:52:18] [main/INFO]: [Indigo] Compatibility mode enabled.
[23:52:18] [main/INFO]: [REI] Config is loaded.
[23:52:18] [main/INFO]: LWJGL Version: 3.2.2 build 10
[23:52:20] [main/INFO]: Narrator library for x64 successfully loaded
[23:52:27] [main/INFO]: OpenAL initialized.
[23:52:27] [main/INFO]: Sound engine started
[23:52:28] [main/INFO]: Created: 1024x512 textures-atlas
[23:52:28] [main/INFO]: Created: 256x256 textures/particle-atlas
[23:52:28] [main/INFO]: Created: 256x256 textures/painting-atlas
[23:52:28] [main/INFO]: Created: 256x128 textures/mob_effect-atlas
[23:52:59] [main/INFO]: Stopping!
Le processus s'est arrêté avec le code de d'arrêt 0.

**Comment by modmuss50** [comment]
Fixed please update to this version: https://github.com/modmuss50/OptiFabric/releases/tag/0.7.0
