### ISSUE TITLE
Failed to setup optifine

### ISSUE THREAD

**Issue by Adaliciously** [modmuss50/OptiFabric#97]
```21:50:32.339
Minecraft client fabric-loader-0.7.1+build.173-1.14.4 is ready to start.
21:50:32.339
Starting!
21:50:32.339
Nothing to download!
21:50:32.339
Extracting 7 files!
21:50:32.438
Using default game log configuration client-1.12.xml (outputs XML)
21:50:32.438
Installing versions!
21:50:34.221
Loading for game Minecraft 1.14.4
21:50:37.641
Warnings were found! 
 - Mod amecs conflicts with mod {optifabric @ [*]}, but the conflicting version is present: 0.6.0!
 - Conflicting versions found for fabric-mining-levels-v0: used 0.1.0+59147463, also found 0.1.0+591e97ae42
21:50:37.643
Mod `voxelmap` (1.9.13) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
21:50:37.643
Mod `tweed` (2.2.8) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
21:50:37.643
Mod `cloth` (0.6.0) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
21:50:37.650
[FabricLoader] Loading 45 mods: minecraft@1.14.4, fabric-networking-blockentity-v0@0.2.0+c877038942, fabric-renderer-api-v1@0.1.1+591e97ae42, fabric-keybindings-v0@0.1.1+591e97ae42, fabricloader@0.7.1+build.173, org_zeroturnaround_zt-zip@1.13, fabric-renderer-indigo@0.1.13+591e97ae42, fabric-containers-v0@0.1.2+591e97ae42, fabric-dimensions-v1@0.1.0+369ab22e42, fiber2cloth@1.2.0, fabric-biomes-v1@0.1.0+591e97ae42, fabric-crash-report-info-v1@0.1.1+591e97ae42, fabric-events-interaction-v0@0.1.2+27da48aa46, org_slf4j_slf4j-simple@1.7.29, roughlyenoughitems@3.1.6+build.33, net_fabricmc_stitch@0.3.0.66, fabric-api-base@0.1.1+2ac73e7242, fabric-rendering-v0@0.1.1+591e97ae42, mousewheelie@1.3.5+1.14.4, cloth-config2@1.1.2, amecs@1.2.6+1.14.4, mm@1.8, fabric-rendering-data-attachment-v1@0.1.1+c877038942, fabric-resource-loader-v0@0.1.3+591e97ae42, me_zeroeightsix_fiber@0.6.0-7, fabric-textures-v0@0.1.4+591e97ae42, fabric-content-registries-v0@0.1.1+591e97ae42, fabric-tag-extensions-v0@0.1.1+591e97ae42, optifabric@0.6.0, fabric-rendering-fluids-v1@0.1.2+36f27aa342, fabric-commands-v0@0.1.1+591e97ae42, fabric-registry-sync-v0@0.2.2+591e97ae42, fabric-mining-levels-v0@0.1.0+59147463, voxelmap@1.9.13, fabric-events-lifecycle-v0@0.1.1+591e97ae42, fabric-loot-tables-v1@0.1.0+591e97ae42, fabric@0.4.1+build.245-1.14, org_slf4j_slf4j-api@1.7.29, fabric-item-groups-v0@0.1.0+591e97ae42, fabric-models-v0@0.1.0+591e97ae42, fabric-particles-v1@0.1.1+c877038942, fabric-networking-v0@0.1.3+591e97ae42, fabric-object-builders-v0@0.1.1+591e97ae42, tweed@2.2.8, cloth@0.6.0
21:50:37.654
Mod `net_fabricmc_stitch` (0.3.0.66) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
21:50:37.780
SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/Jedrzej/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8+build.16/sponge-mixin-0.8+build.16.jar Service=Knot/Fabric Env=CLIENT
21:50:39.023
Error encountered during mixin config postInit step'mixins.mm.json': Failed to setup optifine
java.lang.RuntimeException: Failed to setup optifine
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:40)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:289)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:665)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:512)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:409)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:385)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:280)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:191)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.NoClassDefFoundError: org/spongepowered/asm/lib/ClassWriter
	at me.modmuss50.optifabric.mod.OptifineVersion.getJarType(OptifineVersion.java:66)
	at me.modmuss50.optifabric.mod.OptifineVersion.findOptifineJar(OptifineVersion.java:35)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:49)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:28)
	... 16 more
Caused by: java.lang.ClassNotFoundException: org.spongepowered.asm.lib.ClassWriter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more
21:50:39.856

java.lang.NoSuchMethodError: org.spongepowered.asm.mixin.transformer.ext.ITargetClassContext.getClassNode()Lorg/spongepowered/asm/lib/tree/ClassNode;
	at com.chocohead.mm.Extension.postApply(Extension.java:30)
	at org.spongepowered.asm.mixin.transformer.ext.Extensions.postApply(Extensions.java:167)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:344)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Exception in thread "Client thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:195)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:357)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.client.main.Main.main(Main.java:155)
	... 7 more
Caused by: java.lang.NoSuchMethodError: org.spongepowered.asm.mixin.transformer.ext.ITargetClassContext.getClassNode()Lorg/spongepowered/asm/lib/tree/ClassNode;
	at com.chocohead.mm.Extension.postApply(Extension.java:30)
	at org.spongepowered.asm.mixin.transformer.ext.Extensions.postApply(Extensions.java:167)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:344)
	... 14 more
2019-11-21 21:50:39,585 Client Shutdown Thread WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
java.lang.NoSuchMethodError: org.spongepowered.asm.mixin.transformer.ext.ITargetClassContext.getClassNode()Lorg/spongepowered/asm/lib/tree/ClassNode;
	at com.chocohead.mm.Extension.postApply(Extension.java:30)
	at org.spongepowered.asm.mixin.transformer.ext.Extensions.postApply(Extensions.java:167)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:344)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.client.main.Main$2.run(Main.java:138)
21:50:39.856
Process crashed with exit code 1```

**Comment by Adaliciously** [comment]
Downgraded to 0.6.4.
