### ISSUE TITLE
OptiFabric crashing when attempting to start Minecraft.

### ISSUE THREAD

**Issue by spawncampingnoob** [modmuss50/OptiFabric#98]
Sorry if ths has already been adressed, but whenever I try to open OptiFabric in the Minecraft Launcher, it just crashes before it even opens.

**Comment by Evska1** [comment]
Same for me it doesn't come up with a log  [https://cdn.discordapp.com/attachments/592036249334841361/647776081448796181/unknown.png](url)

**Comment by SilverAndro** [comment]
Same here, heres what seems to be the relevant part in the debug log

```
08:21:41.206
SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/<User>/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8+build.16/sponge-mixin-0.8+build.16.jar Service=Knot/Fabric Env=CLIENT
08:21:41.810
Catching
java.lang.NoClassDefFoundError: org/spongepowered/asm/lib/tree/InsnList
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initInjectionPoint(MixinConfig.java:544)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initInjectionPoints(MixinConfig.java:523)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:390)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1082)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.launch.common.FabricMixinBootstrap.addConfiguration(FabricMixinBootstrap.java:44)
	at net.fabricmc.loader.launch.common.FabricMixinBootstrap$$Lambda$60/1678046232.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.fabricmc.loader.launch.common.FabricMixinBootstrap.init(FabricMixinBootstrap.java:83)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.ClassNotFoundException: org.spongepowered.asm.lib.tree.InsnList
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more
08:21:42.331
Error encountered during mixin config postInit step'mixins.mm.json': Failed to setup optifine
java.lang.RuntimeException: Failed to setup optifine
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:40)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:289)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:665)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:512)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:409)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:385)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:280)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:191)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.NoClassDefFoundError: org/spongepowered/asm/lib/ClassWriter
	at me.modmuss50.optifabric.mod.OptifineVersion.getJarType(OptifineVersion.java:66)
	at me.modmuss50.optifabric.mod.OptifineVersion.findOptifineJar(OptifineVersion.java:35)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:49)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:28)
	... 16 more
Caused by: java.lang.ClassNotFoundException: org.spongepowered.asm.lib.ClassWriter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more
08:21:42.793

java.lang.NoSuchMethodError: org.spongepowered.asm.mixin.transformer.ext.ITargetClassContext.getClassNode()Lorg/spongepowered/asm/lib/tree/ClassNode;
	at com.chocohead.mm.Extension.postApply(Extension.java:30)
	at org.spongepowered.asm.mixin.transformer.ext.Extensions.postApply(Extensions.java:167)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:344)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Exception in thread "Client thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:195)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:357)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.client.main.Main.main(Main.java:155)
	... 7 more
Caused by: java.lang.NoSuchMethodError: org.spongepowered.asm.mixin.transformer.ext.ITargetClassContext.getClassNode()Lorg/spongepowered/asm/lib/tree/ClassNode;
	at com.chocohead.mm.Extension.postApply(Extension.java:30)
	at org.spongepowered.asm.mixin.transformer.ext.Extensions.postApply(Extensions.java:167)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:344)
	... 14 more
2019-11-23 08:21:42,726 Client Shutdown Thread WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
java.lang.NoSuchMethodError: org.spongepowered.asm.mixin.transformer.ext.ITargetClassContext.getClassNode()Lorg/spongepowered/asm/lib/tree/ClassNode;
	at com.chocohead.mm.Extension.postApply(Extension.java:30)
	at org.spongepowered.asm.mixin.transformer.ext.Extensions.postApply(Extensions.java:167)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:344)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.client.main.Main$2.run(Main.java:138)
08:21:42.793
Process crashed with exit code 1
```

**Comment by spawncampingnoob** [comment]
The problem might be where I was using the mod with the default Minecraft launcher, as it runs fine on MultiMC.
(not my) Tutorial on OptiFabric with MultiMC: https://www.youtube.com/watch?v=CRDRv7wLCP0

**Comment by Diamondman121314** [comment]
The problem is using launcher 0.7.0, I'm pretty sure. Use 0.6.4+build.170 instead from https://fabricmc.net/use/.

**Comment by modmuss50** [comment]
Fixed please update to this version: https://github.com/modmuss50/OptiFabric/releases/tag/0.7.0

**Comment by 420mokewed** [comment]
Now it crashes in MultiMC...
Jeez, all I wanted to do was use Immersive Portals on my shitty computer.
